use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use anyhow::{anyhow, Context, Result};
use dialoguer::{theme::ColorfulTheme, Confirm, Input, MultiSelect, Password, Select};

use crate::config::{FieldSource, FieldSourceType, GitHubMode, TrackerSettings};
use crate::deploy::DeployMode;
use crate::doctor::{self, DoctorFormat, DoctorOptions};
use crate::github::{GitHubTracker, ProjectStatusOverview};
use crate::providers::{self, ProviderSetupConfig};

#[derive(Debug, Clone)]
pub struct SetupOptions {
    pub mode: Option<DeployMode>,
    pub workflow: Option<PathBuf>,
    pub env_file: Option<PathBuf>,
    pub service_unit: Option<PathBuf>,
    pub binary_path: Option<PathBuf>,
    pub non_interactive: bool,
}

#[derive(Debug, Clone)]
struct SetupValues {
    tracker_mode: GitHubMode,
    project_status: ProjectStatusConfig,
    normalize_project_statuses: bool,
    provider: String,
    provider_configs: Vec<ProviderSetupConfig>,
    github_owner: String,
    github_repo: String,
    github_project_owner: String,
    github_project_number: String,
    github_project_url: String,
    workspace_root: String,
    seed_repo: String,
    git_clone_url: String,
    assignee_login: String,
    max_concurrent_agents: String,
    max_turns: String,
    github_token: String,
    anthropic_api_key: String,
    gemini_api_key: String,
    openai_api_key: String,
    rust_log: String,
    binary_path: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum ProjectOwnerKind {
    User,
    Organization,
}

#[derive(Debug, Clone)]
struct ProjectStatusConfig {
    active_states: Vec<String>,
    terminal_states: Vec<String>,
    claimable_states: Vec<String>,
    in_progress_state: Option<String>,
    human_review_state: Option<String>,
    done_state: Option<String>,
}

const REMOTE_DOCKER_WORKFLOW_PLACEHOLDER: &str = r#"# Generated placeholder for remote Kairastra install.
# The setup wizard will replace this file.
"#;

const REMOTE_DOCKER_ENV_BOOTSTRAP_PREFIX: &str = r#"# Bootstrap env generated by install-remote-docker.sh.
# Re-run `kairastra setup --mode docker` to replace this file with a fully configured version.
"#;

const GITHUB_TOKEN_SETTINGS_URL: &str = "https://github.com/settings/tokens";
const GITHUB_TOKEN_CLASSIC_URL: &str = "https://github.com/settings/tokens/new";

pub async fn run(options: SetupOptions) -> Result<()> {
    let layout = detect_layout(&std::env::current_dir()?);
    let mode = choose_mode(options.mode, options.non_interactive)?;
    let workflow_path = resolve_workflow_path(&layout, options.workflow.as_ref());
    let env_file_path = resolve_env_file_path(&layout, mode, options.env_file.as_ref());
    let service_unit_path = if mode == DeployMode::Native {
        Some(resolve_service_path(&layout, options.service_unit.as_ref()))
    } else {
        None
    };

    let values =
        collect_values(mode, options.binary_path.as_ref(), options.non_interactive).await?;

    if values.normalize_project_statuses {
        normalize_project_statuses(&layout, &values)?;
    }

    write_text_file(
        &workflow_path,
        &render_workflow(mode, &values),
        options.non_interactive,
    )?;
    write_text_file(
        &env_file_path,
        &render_env_file(mode, &values, &workflow_path),
        options.non_interactive,
    )?;

    if let Some(path) = service_unit_path.as_ref() {
        let unit = render_systemd_unit(&values, &workflow_path, &env_file_path);
        write_text_file(path, &unit, options.non_interactive)?;
    }

    doctor::run(DoctorOptions {
        workflow: Some(workflow_path.clone()),
        env_file: Some(env_file_path.clone()),
        mode: Some(mode),
        format: DoctorFormat::Text,
    })
    .await
    .context("generated files failed doctor validation")?;

    println!();
    println!("Generated:");
    println!("- workflow: {}", workflow_path.display());
    println!("- env file: {}", env_file_path.display());
    let provider_auth_ready = providers::inspect_auth_status(&values.provider)
        .map(|status| status.credentials_present)
        .unwrap_or(false);

    if let Some(path) = service_unit_path.as_ref() {
        println!("- systemd unit: {}", path.display());
        println!("Next steps:");
        let mut step = 1;
        if !provider_auth_ready {
            println!(
                "{}. Initialize provider auth later if needed: {}",
                step,
                native_login_command(&values.provider)
            );
            step += 1;
        }
        println!(
            "{step}. Install the unit: sudo cp {} /etc/systemd/system/kairastra.service",
            path.display()
        );
        println!("{}. Reload systemd: sudo systemctl daemon-reload", step + 1);
        println!(
            "{}. Start Kairastra: sudo systemctl enable --now kairastra.service",
            step + 2
        );
    } else {
        println!("Next steps:");
        println!(
            "1. Review {} and {}",
            workflow_path.display(),
            env_file_path.display()
        );
        let mut step = 2;
        if !provider_auth_ready {
            println!(
                "{}. Initialize provider auth later if needed: {}",
                step,
                docker_login_command(&layout, &values.provider)
            );
            step += 1;
        }
        println!(
            "{}. Start Docker mode: {}",
            step,
            docker_make_command(&layout, "docker-up")
        );
    }

    Ok(())
}

fn choose_mode(explicit: Option<DeployMode>, non_interactive: bool) -> Result<DeployMode> {
    if let Some(mode) = explicit {
        return Ok(mode);
    }

    if non_interactive {
        return Ok(if Path::new("rust/compose.yml").is_file() {
            DeployMode::Docker
        } else {
            DeployMode::Native
        });
    }

    let options = [DeployMode::Native, DeployMode::Docker];
    let labels = ["Native VPS (systemd)", "Docker Compose"];
    let selection = Select::with_theme(&ColorfulTheme::default())
        .with_prompt("Deployment mode")
        .items(&labels)
        .default(0)
        .interact()?;
    Ok(options[selection])
}

#[derive(Debug, Clone)]
struct SetupLayout {
    repo_root: PathBuf,
    rust_dir: PathBuf,
}

fn detect_layout(cwd: &Path) -> SetupLayout {
    if cwd.file_name().and_then(|name| name.to_str()) == Some("rust")
        && cwd.join("Cargo.toml").is_file()
        && cwd.join("compose.yml").is_file()
    {
        return SetupLayout {
            repo_root: cwd.parent().unwrap_or(cwd).to_path_buf(),
            rust_dir: cwd.to_path_buf(),
        };
    }

    if cwd.join("rust/Cargo.toml").is_file() && cwd.join("rust/compose.yml").is_file() {
        return SetupLayout {
            repo_root: cwd.to_path_buf(),
            rust_dir: cwd.join("rust"),
        };
    }

    SetupLayout {
        repo_root: cwd.to_path_buf(),
        rust_dir: cwd.to_path_buf(),
    }
}

fn resolve_workflow_path(layout: &SetupLayout, explicit: Option<&PathBuf>) -> PathBuf {
    if let Some(path) = explicit {
        return path.clone();
    }

    layout.repo_root.join("WORKFLOW.md")
}

fn resolve_env_file_path(
    layout: &SetupLayout,
    mode: DeployMode,
    explicit: Option<&PathBuf>,
) -> PathBuf {
    if let Some(path) = explicit {
        return path.clone();
    }

    match mode {
        DeployMode::Native => layout.repo_root.join("kairastra.env"),
        DeployMode::Docker => {
            let default = layout.rust_dir.join(".env");
            if default.exists() {
                layout.rust_dir.join(".env.generated")
            } else {
                default
            }
        }
    }
}

fn resolve_service_path(layout: &SetupLayout, explicit: Option<&PathBuf>) -> PathBuf {
    explicit
        .cloned()
        .unwrap_or_else(|| layout.repo_root.join("kairastra.service"))
}

fn docker_make_command(layout: &SetupLayout, target: &str) -> String {
    if layout.repo_root == layout.rust_dir {
        format!("make {}", target)
    } else {
        format!("make -C {} {}", layout.rust_dir.display(), target)
    }
}

fn docker_login_command(layout: &SetupLayout, provider: &str) -> String {
    format!(
        "{} PROVIDER={provider}",
        docker_make_command(layout, "docker-login")
    )
}

fn native_login_command(provider: &str) -> String {
    format!("kairastra auth --provider {provider} login --mode subscription")
}

async fn collect_values(
    mode: DeployMode,
    explicit_binary_path: Option<&PathBuf>,
    non_interactive: bool,
) -> Result<SetupValues> {
    let cwd = std::env::current_dir()?;
    let theme = ColorfulTheme::default();
    let env_github_owner = std::env::var("KAIRASTRA_GITHUB_OWNER").unwrap_or_default();
    let env_github_repo = std::env::var("KAIRASTRA_GITHUB_REPO").unwrap_or_default();
    let env_project_owner = std::env::var("KAIRASTRA_GITHUB_PROJECT_OWNER").unwrap_or_default();
    let env_project_number = std::env::var("KAIRASTRA_GITHUB_PROJECT_NUMBER").unwrap_or_default();
    let env_project_url = std::env::var("KAIRASTRA_GITHUB_PROJECT_URL").unwrap_or_default();
    let env_git_clone_url = std::env::var("KAIRASTRA_GIT_CLONE_URL").unwrap_or_default();
    let repo_input = ask_string(
        &theme,
        "GitHub repo to manage (name or GitHub URL)",
        env_github_repo,
        non_interactive,
        false,
    )?;
    let parsed_repo = parse_repo_input(&repo_input);
    let tracker_mode = choose_tracker_mode(
        &theme,
        non_interactive,
        !env_project_number.trim().is_empty() || !env_project_url.trim().is_empty(),
    )?;
    let github_project_url = if tracker_mode == GitHubMode::ProjectsV2 {
        ask_string(
            &theme,
            "GitHub Project URL (optional, auto-fills project owner and number)",
            env_project_url,
            non_interactive,
            true,
        )?
    } else {
        String::new()
    };
    let parsed_project = parse_project_url(&github_project_url);
    let github_owner = if !env_github_owner.trim().is_empty() {
        env_github_owner
    } else if let Some(parsed) = parsed_repo.as_ref().and_then(|parsed| parsed.owner.clone()) {
        parsed
    } else if let Some(parsed) = parsed_project.as_ref() {
        parsed.owner.clone()
    } else {
        ask_string(
            &theme,
            "GitHub owner",
            String::new(),
            non_interactive,
            false,
        )?
    };
    let github_repo = parsed_repo
        .as_ref()
        .map(|parsed| parsed.repo.clone())
        .unwrap_or(repo_input);
    let github_project_owner = if tracker_mode == GitHubMode::ProjectsV2 {
        if !env_project_owner.trim().is_empty() {
            env_project_owner
        } else if let Some(parsed) = parsed_project.as_ref() {
            parsed.owner.clone()
        } else {
            ask_string(
                &theme,
                "GitHub Project owner (leave blank to use GitHub owner)",
                github_owner.clone(),
                non_interactive,
                false,
            )?
        }
    } else {
        String::new()
    };
    let github_project_number = if tracker_mode == GitHubMode::ProjectsV2 {
        if !env_project_number.trim().is_empty() {
            env_project_number
        } else if let Some(parsed) = parsed_project.as_ref() {
            parsed.project_number.clone()
        } else {
            ask_string(
                &theme,
                "GitHub Project v2 number",
                String::new(),
                non_interactive,
                false,
            )?
        }
    } else {
        String::new()
    };
    let github_token = resolve_github_token(
        &theme,
        non_interactive,
        github_token_help_context(tracker_mode, parsed_project.as_ref()),
    )?;
    let project_status_overview = if tracker_mode == GitHubMode::ProjectsV2 {
        inspect_project_status_overview(
            &github_token,
            &github_owner,
            &github_repo,
            &github_project_owner,
            &github_project_number,
            &github_project_url,
        )
        .await
        .ok()
    } else {
        None
    };
    let (project_status, normalize_project_statuses) = collect_project_status_config(
        &theme,
        non_interactive,
        project_status_overview.as_ref(),
        &github_owner,
        &github_project_owner,
        &github_project_number,
    )?;
    let workspace_root = std::env::var("KAIRASTRA_WORKSPACE_ROOT").unwrap_or_else(|_| match mode {
        DeployMode::Native => "/var/lib/kairastra/workspaces".to_string(),
        DeployMode::Docker => "/workspaces".to_string(),
    });
    let seed_repo = if mode == DeployMode::Native {
        ask_string(
            &theme,
            "Seed repo path (host checkout or overlay repo)",
            std::env::var("KAIRASTRA_SEED_REPO")
                .ok()
                .filter(|value| !value.trim().is_empty())
                .unwrap_or_else(|| cwd.display().to_string()),
            non_interactive,
            false,
        )?
    } else {
        "/seed-repo".to_string()
    };
    let git_clone_url = default_target_clone_url(&env_git_clone_url, &github_owner, &github_repo);
    let assignee_login = std::env::var("KAIRASTRA_AGENT_ASSIGNEE").unwrap_or_default();
    let max_concurrent_agents = "4".to_string();
    let max_turns = "20".to_string();
    let provider = choose_provider(&theme, non_interactive)?;
    let provider_configs = collect_provider_configs(&provider, non_interactive)?;
    let anthropic_api_key = std::env::var("ANTHROPIC_API_KEY").unwrap_or_default();
    let gemini_api_key = std::env::var("GEMINI_API_KEY")
        .or_else(|_| std::env::var("GOOGLE_API_KEY"))
        .unwrap_or_default();
    let openai_api_key = std::env::var("OPENAI_API_KEY").unwrap_or_default();
    let rust_log = std::env::var("RUST_LOG").unwrap_or_else(|_| "info".to_string());
    let binary_path = detect_binary_path(explicit_binary_path);

    Ok(SetupValues {
        tracker_mode,
        project_status,
        normalize_project_statuses,
        provider,
        provider_configs,
        github_owner,
        github_repo,
        github_project_owner,
        github_project_number,
        github_project_url,
        workspace_root,
        seed_repo,
        git_clone_url,
        assignee_login,
        max_concurrent_agents,
        max_turns,
        github_token,
        anthropic_api_key,
        gemini_api_key,
        openai_api_key,
        rust_log,
        binary_path,
    })
}

fn choose_tracker_mode(
    theme: &ColorfulTheme,
    non_interactive: bool,
    prefer_projects_v2: bool,
) -> Result<GitHubMode> {
    if non_interactive {
        return Ok(if prefer_projects_v2 {
            GitHubMode::ProjectsV2
        } else {
            GitHubMode::IssuesOnly
        });
    }

    let options = [GitHubMode::IssuesOnly, GitHubMode::ProjectsV2];
    let labels = [
        "Repository issues only (recommended)",
        "GitHub Project v2 queue",
    ];
    let default = if prefer_projects_v2 { 1 } else { 0 };
    let selection = Select::with_theme(theme)
        .with_prompt("Queue source")
        .items(&labels)
        .default(default)
        .interact()?;
    Ok(options[selection])
}

fn collect_provider_configs(
    selected_provider: &str,
    non_interactive: bool,
) -> Result<Vec<ProviderSetupConfig>> {
    let mut configs = Vec::new();
    for (provider, _) in providers::setup_provider_choices() {
        let provider_non_interactive = non_interactive || *provider != selected_provider;
        configs.push(providers::collect_setup_config(
            provider,
            provider_non_interactive,
        )?);
    }
    Ok(configs)
}

fn choose_provider(theme: &ColorfulTheme, non_interactive: bool) -> Result<String> {
    let env_provider = std::env::var("KAIRASTRA_AGENT_PROVIDER")
        .ok()
        .map(|value| value.trim().to_ascii_lowercase())
        .filter(|value| !value.is_empty());
    if non_interactive {
        return Ok(env_provider.unwrap_or_else(|| providers::default_setup_provider().to_string()));
    }

    let choices = providers::setup_provider_choices();
    let default_provider =
        env_provider.unwrap_or_else(|| providers::default_setup_provider().to_string());
    let default_index = choices
        .iter()
        .position(|(provider, _)| *provider == default_provider)
        .unwrap_or(0);
    let labels = choices.iter().map(|(_, label)| *label).collect::<Vec<_>>();
    let selection = Select::with_theme(theme)
        .with_prompt("Agent provider")
        .items(&labels)
        .default(default_index)
        .interact()?;
    Ok(choices[selection].0.to_string())
}

fn detect_binary_path(explicit: Option<&PathBuf>) -> String {
    if let Some(path) = explicit {
        return path.display().to_string();
    }

    if let Ok(path) = std::env::var("KAIRASTRA_BINARY_PATH") {
        let trimmed = path.trim();
        if !trimmed.is_empty() {
            return trimmed.to_string();
        }
    }

    if let Ok(path) = std::env::current_exe() {
        let rendered = path.display().to_string();
        if !rendered.contains("/target/debug/") && !rendered.contains("/target/release/") {
            return rendered;
        }
    }

    "/usr/local/bin/kairastra".to_string()
}

fn default_target_clone_url(existing: &str, owner: &str, repo: &str) -> String {
    let trimmed_existing = existing.trim();
    if trimmed_existing.is_empty() {
        return format!("https://github.com/{owner}/{repo}.git");
    }

    let existing_repo = parse_repo_input(trimmed_existing);
    if existing_repo
        .as_ref()
        .and_then(|parsed| parsed.owner.as_deref())
        == Some(owner)
        && existing_repo.as_ref().map(|parsed| parsed.repo.as_str()) == Some(repo)
    {
        trimmed_existing.to_string()
    } else {
        format!("https://github.com/{owner}/{repo}.git")
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct ParsedProjectUrl {
    owner: String,
    project_number: String,
    owner_kind: ProjectOwnerKind,
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct ParsedRepoInput {
    owner: Option<String>,
    repo: String,
}

fn parse_project_url(url: &str) -> Option<ParsedProjectUrl> {
    let trimmed = url.trim();
    if trimmed.is_empty() {
        return None;
    }

    let without_scheme = trimmed
        .strip_prefix("https://")
        .or_else(|| trimmed.strip_prefix("http://"))
        .unwrap_or(trimmed);
    let without_host = without_scheme
        .strip_prefix("github.com/")
        .or_else(|| without_scheme.strip_prefix("www.github.com/"))?;
    let path = without_host
        .split(['?', '#'])
        .next()
        .unwrap_or(without_host);
    let segments: Vec<&str> = path
        .split('/')
        .filter(|segment| !segment.is_empty())
        .collect();
    if segments.len() < 4 {
        return None;
    }
    if segments[0] != "users" && segments[0] != "orgs" {
        return None;
    }
    if segments[2] != "projects" {
        return None;
    }

    let project_number = segments[3];
    if project_number.parse::<u32>().is_err() {
        return None;
    }

    let owner_kind = match segments[0] {
        "users" => ProjectOwnerKind::User,
        "orgs" => ProjectOwnerKind::Organization,
        _ => return None,
    };

    Some(ParsedProjectUrl {
        owner: segments[1].to_string(),
        project_number: project_number.to_string(),
        owner_kind,
    })
}

fn parse_repo_input(value: &str) -> Option<ParsedRepoInput> {
    let trimmed = value.trim();
    if trimmed.is_empty() {
        return None;
    }

    let without_host = if let Some(path) = trimmed.strip_prefix("git@github.com:") {
        path
    } else if let Some(path) = trimmed.strip_prefix("ssh://git@github.com/") {
        path
    } else {
        let without_scheme = trimmed
            .strip_prefix("https://")
            .or_else(|| trimmed.strip_prefix("http://"))
            .unwrap_or(trimmed);
        without_scheme
            .strip_prefix("github.com/")
            .or_else(|| without_scheme.strip_prefix("www.github.com/"))?
    };
    let path = without_host
        .split(['?', '#'])
        .next()
        .unwrap_or(without_host);
    let segments: Vec<&str> = path
        .split('/')
        .filter(|segment| !segment.is_empty())
        .collect();
    if segments.len() < 2 {
        return None;
    }

    let repo = segments[1].trim_end_matches(".git");
    if repo.is_empty() {
        return None;
    }

    Some(ParsedRepoInput {
        owner: Some(segments[0].to_string()),
        repo: repo.to_string(),
    })
}

fn ask_string(
    theme: &ColorfulTheme,
    prompt: &str,
    default: String,
    non_interactive: bool,
    allow_empty: bool,
) -> Result<String> {
    if non_interactive {
        return Ok(default);
    }

    let mut input = Input::<String>::with_theme(theme);
    input = input.with_prompt(prompt).default(default.clone());
    let value = input.interact_text()?;
    if allow_empty || !value.trim().is_empty() {
        Ok(value.trim().to_string())
    } else {
        Ok(default)
    }
}

fn ask_string_list(
    theme: &ColorfulTheme,
    prompt: &str,
    default: &[String],
    non_interactive: bool,
) -> Result<Vec<String>> {
    let rendered_default = default.join(", ");
    let value = ask_string(theme, prompt, rendered_default, non_interactive, true)?;
    Ok(parse_string_list(&value))
}

fn ask_optional_string(
    theme: &ColorfulTheme,
    prompt: &str,
    default: Option<&str>,
    non_interactive: bool,
) -> Result<Option<String>> {
    let value = ask_string(
        theme,
        prompt,
        default.unwrap_or_default().to_string(),
        non_interactive,
        true,
    )?;
    if value.trim().is_empty() {
        Ok(None)
    } else {
        Ok(Some(value))
    }
}

fn parse_string_list(value: &str) -> Vec<String> {
    value
        .split(',')
        .map(str::trim)
        .filter(|value| !value.is_empty())
        .map(ToString::to_string)
        .collect()
}

fn parse_list_env(name: &str) -> Option<Vec<String>> {
    std::env::var(name)
        .ok()
        .map(|value| parse_string_list(&value))
        .filter(|values| !values.is_empty())
}

fn parse_optional_env(name: &str) -> Option<Option<String>> {
    let value = std::env::var(name).ok()?;
    let trimmed = value.trim();
    if trimmed.is_empty()
        || trimmed.eq_ignore_ascii_case("none")
        || trimmed.eq_ignore_ascii_case("null")
    {
        return Some(None);
    }
    Some(Some(trimmed.to_string()))
}

fn resolve_env_secret(names: &[&str]) -> Option<String> {
    names.iter().find_map(|name| {
        std::env::var(name)
            .ok()
            .map(|value| value.trim().to_string())
            .filter(|value| !value.is_empty())
    })
}

fn print_setup_help_block<T: AsRef<str>>(title: &str, lines: &[T]) {
    println!();
    println!("{title}");
    for line in lines {
        println!("{}", line.as_ref());
    }
    println!();
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum ProjectStatusHelpTopic {
    Handling,
    ActiveStates,
    TerminalStates,
    ClaimableStates,
    InProgressState,
    HumanReviewState,
    DoneState,
}

fn project_status_help_title(topic: ProjectStatusHelpTopic) -> &'static str {
    match topic {
        ProjectStatusHelpTopic::Handling => "Project status handling",
        ProjectStatusHelpTopic::ActiveStates => "Dispatchable active states",
        ProjectStatusHelpTopic::TerminalStates => "Terminal states",
        ProjectStatusHelpTopic::ClaimableStates => "States treated as ready to claim",
        ProjectStatusHelpTopic::InProgressState => "Status to set when a claim starts",
        ProjectStatusHelpTopic::HumanReviewState => "Status to set for review or blocked handoff",
        ProjectStatusHelpTopic::DoneState => "Status to set when a closed issue is reconciled",
    }
}

fn project_status_help_lines(topic: ProjectStatusHelpTopic) -> Vec<&'static str> {
    match topic {
        ProjectStatusHelpTopic::Handling => vec![
            "- Choose whether Kairastra should map onto your existing Project statuses or rewrite the Project to Kairastra's default status set.",
            "- Keeping existing statuses is the safe default and does not mutate GitHub.",
        ],
        ProjectStatusHelpTopic::ActiveStates => vec![
            "- Pick the Project statuses Kairastra should treat as still in the working queue.",
            "- Only items in these active states are polled and dispatched until they move to a terminal state.",
        ],
        ProjectStatusHelpTopic::TerminalStates => vec![
            "- Pick the statuses Kairastra should treat as final or no longer dispatchable.",
            "- Closed issues and completed Project items should end up in one of these states.",
        ],
        ProjectStatusHelpTopic::ClaimableStates => vec![
            "- Optionally choose the subset of active states that mean an issue is ready to claim right now.",
            "- Leave this empty if any active state should be considered claimable.",
        ],
        ProjectStatusHelpTopic::InProgressState => vec![
            "- Choose the Project status Kairastra should set automatically when work begins on a claimed issue.",
            "- Select `Do not change project status` to leave the status untouched at claim time.",
        ],
        ProjectStatusHelpTopic::HumanReviewState => vec![
            "- Choose the Project status Kairastra should set when work needs human follow-up, review, or a blocked handoff.",
            "- Select `Do not change project status` to disable that automatic transition.",
        ],
        ProjectStatusHelpTopic::DoneState => vec![
            "- Choose the Project status Kairastra should set after it sees the issue is closed and reconciles the Project item.",
            "- Select `Do not change project status` to keep the Project status unchanged when the issue closes.",
        ],
    }
}

fn print_project_status_help(topic: ProjectStatusHelpTopic) {
    print_setup_help_block(
        project_status_help_title(topic),
        &project_status_help_lines(topic),
    );
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
struct GitHubTokenHelpContext {
    tracker_mode: GitHubMode,
    project_owner_kind: Option<ProjectOwnerKind>,
}

fn github_token_help_context(
    tracker_mode: GitHubMode,
    parsed_project: Option<&ParsedProjectUrl>,
) -> GitHubTokenHelpContext {
    GitHubTokenHelpContext {
        tracker_mode,
        project_owner_kind: parsed_project.map(|project| project.owner_kind),
    }
}

fn github_token_tracker_guidance(context: GitHubTokenHelpContext) -> &'static str {
    match context {
        GitHubTokenHelpContext {
            tracker_mode: GitHubMode::ProjectsV2,
            project_owner_kind: Some(ProjectOwnerKind::User),
        } => "A GitHub token is required. User-owned Projects v2 require a classic PAT.",
        GitHubTokenHelpContext {
            tracker_mode: GitHubMode::ProjectsV2,
            project_owner_kind: Some(ProjectOwnerKind::Organization),
        } => "A GitHub token is required. Org-owned Projects v2 can use a classic PAT, and may support a fine-grained PAT when the org exposes the Projects permission.",
        GitHubTokenHelpContext {
            tracker_mode: GitHubMode::ProjectsV2,
            project_owner_kind: None,
        } => {
            "A GitHub token is required. User-owned Projects v2 require a classic PAT; org-owned Projects v2 can use a classic PAT and may support a fine-grained PAT when the org exposes the Projects permission."
        }
        GitHubTokenHelpContext {
            tracker_mode: GitHubMode::IssuesOnly,
            ..
        } => {
            "A GitHub token is required so Kairastra can read issues and clone/push against the target repo."
        }
    }
}

fn github_token_help_lines(context: GitHubTokenHelpContext) -> Vec<String> {
    let mut lines = vec![
        format!("- Token settings: {GITHUB_TOKEN_SETTINGS_URL}"),
        format!("- Classic token creation: {GITHUB_TOKEN_CLASSIC_URL}"),
        "- Existing GITHUB_TOKEN or GH_TOKEN env vars will skip this prompt.".to_string(),
    ];

    match context {
        GitHubTokenHelpContext {
            tracker_mode: GitHubMode::ProjectsV2,
            project_owner_kind: Some(ProjectOwnerKind::User),
        } => {
            lines.extend([
                "- For user-owned Projects v2, use a classic PAT, not a fine-grained PAT."
                    .to_string(),
                "- Recommended scopes: `project`, `repo` for private repos, and `workflow` when pushes may edit `.github/workflows/*`."
                    .to_string(),
                "- For read-only diagnostics, `read:project` can replace `project`.".to_string(),
            ]);
        }
        GitHubTokenHelpContext {
            tracker_mode: GitHubMode::ProjectsV2,
            project_owner_kind: Some(ProjectOwnerKind::Organization),
        } => {
            lines.extend([
                "- For org-owned Projects v2, a fine-grained PAT may work when the org exposes the `Projects` permission; a classic PAT also works."
                    .to_string(),
                "- If you use a fine-grained PAT, look for the org-level `Projects` permission. If it is missing, create a classic PAT instead."
                    .to_string(),
                "- Recommended classic PAT scopes: `project`, `repo` for private repos, and `workflow` when pushes may edit `.github/workflows/*`."
                    .to_string(),
                "- For read-only diagnostics with a classic PAT, `read:project` can replace `project`.".to_string(),
            ]);
        }
        GitHubTokenHelpContext {
            tracker_mode: GitHubMode::ProjectsV2,
            project_owner_kind: None,
        } => {
            lines.extend([
                "- User-owned Projects v2 require a classic PAT; org-owned Projects v2 may work with a fine-grained PAT when the org exposes the `Projects` permission."
                    .to_string(),
                "- If you do not see a `Projects` permission while creating a fine-grained PAT, create a classic PAT instead."
                    .to_string(),
                "- Recommended classic PAT scopes: `project`, `repo` for private repos, and `workflow` when pushes may edit `.github/workflows/*`."
                    .to_string(),
                "- For read-only diagnostics with a classic PAT, `read:project` can replace `project`.".to_string(),
            ]);
        }
        GitHubTokenHelpContext {
            tracker_mode: GitHubMode::IssuesOnly,
            ..
        } => {
            lines.extend([
                "- Recommended scopes: `repo` for private repos and `workflow` only when pushes may edit `.github/workflows/*`."
                    .to_string(),
                "- Public repos can often work without `repo`, but private repos need it."
                    .to_string(),
            ]);
        }
    }

    lines.extend([
        "- If the repo or project belongs to an org with SSO, authorize the token for SSO after creating it.".to_string(),
        "- More details: rust/README.md and docs/troubleshooting.md".to_string(),
    ]);
    lines
}

fn github_token_error_guidance(context: GitHubTokenHelpContext, non_interactive: bool) -> String {
    let action = if non_interactive {
        "Set GITHUB_TOKEN or GH_TOKEN before running setup."
    } else {
        "Provide a non-empty token."
    };
    format!(
        "{} {} Create or review tokens at {} or {}. See rust/README.md and docs/troubleshooting.md for scope details.",
        github_token_tracker_guidance(context),
        action,
        GITHUB_TOKEN_SETTINGS_URL,
        GITHUB_TOKEN_CLASSIC_URL
    )
}

fn resolve_github_token(
    theme: &ColorfulTheme,
    non_interactive: bool,
    help_context: GitHubTokenHelpContext,
) -> Result<String> {
    if let Some(token) = resolve_env_secret(&["GITHUB_TOKEN", "GH_TOKEN"]) {
        return Ok(token);
    }

    if non_interactive {
        return Err(anyhow!(github_token_error_guidance(help_context, true)));
    }

    let help_lines = github_token_help_lines(help_context);
    print_setup_help_block("GitHub token setup", &help_lines);

    let token = Password::with_theme(theme)
        .with_prompt("GitHub token")
        .allow_empty_password(true)
        .interact()?;
    let token = token.trim().to_string();
    if token.is_empty() {
        return Err(anyhow!(github_token_error_guidance(help_context, false)));
    }

    Ok(token)
}

fn canonical_project_status_options() -> Vec<String> {
    vec![
        "Backlog".to_string(),
        "Todo".to_string(),
        "In Progress".to_string(),
        "Human Review".to_string(),
        "Merging".to_string(),
        "Rework".to_string(),
        "Done".to_string(),
        "Cancelled".to_string(),
        "Duplicate".to_string(),
    ]
}

fn canonical_project_status_config() -> ProjectStatusConfig {
    ProjectStatusConfig {
        active_states: vec![
            "Todo".to_string(),
            "In Progress".to_string(),
            "Merging".to_string(),
            "Rework".to_string(),
        ],
        terminal_states: vec![
            "Closed".to_string(),
            "Cancelled".to_string(),
            "Duplicate".to_string(),
            "Done".to_string(),
        ],
        claimable_states: vec!["Todo".to_string()],
        in_progress_state: Some("In Progress".to_string()),
        human_review_state: Some("Human Review".to_string()),
        done_state: Some("Done".to_string()),
    }
}

fn status_normalization_confirmation_token(project_owner: &str, project_number: &str) -> String {
    format!("normalize {project_owner}#{project_number}")
}

fn project_status_overview_block_reason(overview: &ProjectStatusOverview) -> Option<String> {
    if overview.total_items == 0 {
        return None;
    }

    let canonical = canonical_project_status_options()
        .into_iter()
        .map(|value| value.to_ascii_lowercase())
        .collect::<Vec<_>>();
    let incompatible = overview
        .item_counts
        .keys()
        .filter(|status| {
            !canonical
                .iter()
                .any(|candidate| candidate == &status.to_ascii_lowercase())
        })
        .cloned()
        .collect::<Vec<_>>();
    if incompatible.is_empty() {
        None
    } else {
        Some(format!(
            "normalization is blocked because this Project already has items in statuses that would be changed or removed: {}",
            incompatible.join(", ")
        ))
    }
}

fn build_project_status_tracker_settings(
    github_token: &str,
    github_owner: &str,
    github_repo: &str,
    github_project_owner: &str,
    github_project_number: &str,
    github_project_url: &str,
) -> Option<TrackerSettings> {
    if github_token.trim().is_empty() || github_project_number.trim().is_empty() {
        return None;
    }
    let project_number = github_project_number.trim().parse::<u32>().ok()?;
    Some(TrackerSettings {
        kind: "github".to_string(),
        mode: GitHubMode::ProjectsV2,
        api_key: github_token.to_string(),
        owner: github_owner.to_string(),
        repo: Some(github_repo.to_string()),
        project_owner: Some(github_project_owner.to_string())
            .filter(|value| !value.trim().is_empty()),
        project_v2_number: Some(project_number),
        project_url: Some(github_project_url.to_string()).filter(|value| !value.trim().is_empty()),
        active_states: Vec::new(),
        terminal_states: Vec::new(),
        claimable_states: Vec::new(),
        in_progress_state: None,
        human_review_state: None,
        done_state: None,
        status_source: Some(FieldSource {
            source_type: FieldSourceType::ProjectField,
            name: Some("Status".to_string()),
        }),
        priority_source: None,
        graphql_endpoint: "https://api.github.com/graphql".to_string(),
        rest_endpoint: "https://api.github.com".to_string(),
    })
}

async fn inspect_project_status_overview(
    github_token: &str,
    github_owner: &str,
    github_repo: &str,
    github_project_owner: &str,
    github_project_number: &str,
    github_project_url: &str,
) -> Result<ProjectStatusOverview> {
    let settings = build_project_status_tracker_settings(
        github_token,
        github_owner,
        github_repo,
        github_project_owner,
        github_project_number,
        github_project_url,
    )
    .ok_or_else(|| {
        anyhow!("project status inspection requires GITHUB_TOKEN and a valid project number")
    })?;
    let tracker = GitHubTracker::new(settings)?;
    tracker.inspect_project_status_overview().await
}

fn prompt_multi_select_states(
    theme: &ColorfulTheme,
    prompt: &str,
    options: &[String],
    defaults: &[String],
    counts: Option<&std::collections::HashMap<String, usize>>,
    allow_empty: bool,
) -> Result<Vec<String>> {
    let labels = options
        .iter()
        .map(|option| {
            let count = counts
                .and_then(|counts| counts.get(option))
                .copied()
                .unwrap_or(0);
            if count > 0 {
                format!("{option} ({count} items)")
            } else {
                option.clone()
            }
        })
        .collect::<Vec<_>>();
    let default_checks = options
        .iter()
        .map(|option| {
            defaults
                .iter()
                .any(|candidate| candidate.eq_ignore_ascii_case(option))
        })
        .collect::<Vec<_>>();
    let selections = MultiSelect::with_theme(theme)
        .with_prompt(prompt)
        .items(&labels)
        .defaults(&default_checks)
        .interact()?;
    let chosen = selections
        .into_iter()
        .filter_map(|index| options.get(index).cloned())
        .collect::<Vec<_>>();
    if !allow_empty && chosen.is_empty() {
        return Err(anyhow!("{prompt} requires at least one selection"));
    }
    Ok(chosen)
}

fn prompt_optional_state(
    theme: &ColorfulTheme,
    prompt: &str,
    options: &[String],
    default: Option<&str>,
    counts: Option<&std::collections::HashMap<String, usize>>,
) -> Result<Option<String>> {
    let mut labels = vec!["Do not change project status".to_string()];
    labels.extend(options.iter().map(|option| {
        let count = counts
            .and_then(|counts| counts.get(option))
            .copied()
            .unwrap_or(0);
        if count > 0 {
            format!("{option} ({count} items)")
        } else {
            option.clone()
        }
    }));
    let default_index = default
        .and_then(|target| {
            options
                .iter()
                .position(|option| option.eq_ignore_ascii_case(target))
                .map(|index| index + 1)
        })
        .unwrap_or(0);
    let selection = Select::with_theme(theme)
        .with_prompt(prompt)
        .items(&labels)
        .default(default_index)
        .interact()?;
    if selection == 0 {
        Ok(None)
    } else {
        Ok(options.get(selection - 1).cloned())
    }
}

fn collect_existing_project_status_config(
    theme: &ColorfulTheme,
    overview: &ProjectStatusOverview,
) -> Result<ProjectStatusConfig> {
    let defaults = canonical_project_status_config();
    print_project_status_help(ProjectStatusHelpTopic::ActiveStates);
    let active_states = prompt_multi_select_states(
        theme,
        "Dispatchable active states",
        &overview.options,
        &defaults.active_states,
        Some(&overview.item_counts),
        false,
    )?;
    let mut terminal_options = vec!["Closed".to_string()];
    terminal_options.extend(overview.options.clone());
    print_project_status_help(ProjectStatusHelpTopic::TerminalStates);
    let terminal_states = prompt_multi_select_states(
        theme,
        "Terminal states",
        &terminal_options,
        &defaults.terminal_states,
        Some(&overview.item_counts),
        false,
    )?;
    print_project_status_help(ProjectStatusHelpTopic::ClaimableStates);
    let claimable_states = prompt_multi_select_states(
        theme,
        "States treated as ready to claim (optional)",
        &active_states,
        &defaults.claimable_states,
        Some(&overview.item_counts),
        true,
    )?;
    print_project_status_help(ProjectStatusHelpTopic::InProgressState);
    let in_progress_state = prompt_optional_state(
        theme,
        "Status to set when a claim starts",
        &overview.options,
        defaults.in_progress_state.as_deref(),
        Some(&overview.item_counts),
    )?;
    print_project_status_help(ProjectStatusHelpTopic::HumanReviewState);
    let human_review_state = prompt_optional_state(
        theme,
        "Status to set for review or blocked handoff",
        &overview.options,
        defaults.human_review_state.as_deref(),
        Some(&overview.item_counts),
    )?;
    print_project_status_help(ProjectStatusHelpTopic::DoneState);
    let done_state = prompt_optional_state(
        theme,
        "Status to set when a closed issue is reconciled",
        &overview.options,
        defaults.done_state.as_deref(),
        Some(&overview.item_counts),
    )?;

    Ok(ProjectStatusConfig {
        active_states,
        terminal_states,
        claimable_states,
        in_progress_state,
        human_review_state,
        done_state,
    })
}

fn collect_manual_project_status_config(
    theme: &ColorfulTheme,
    non_interactive: bool,
) -> Result<ProjectStatusConfig> {
    let defaults = canonical_project_status_config();
    print_project_status_help(ProjectStatusHelpTopic::ActiveStates);
    let active_states = ask_string_list(
        theme,
        "Dispatchable active states (comma-separated)",
        &defaults.active_states,
        non_interactive,
    )?;
    print_project_status_help(ProjectStatusHelpTopic::TerminalStates);
    let terminal_states = ask_string_list(
        theme,
        "Terminal states (comma-separated)",
        &defaults.terminal_states,
        non_interactive,
    )?;
    print_project_status_help(ProjectStatusHelpTopic::ClaimableStates);
    let claimable_states = ask_string_list(
        theme,
        "Claimable states (comma-separated, optional)",
        &defaults.claimable_states,
        non_interactive,
    )?;
    print_project_status_help(ProjectStatusHelpTopic::InProgressState);
    let in_progress_state = ask_optional_string(
        theme,
        "Status to set when a claim starts (optional)",
        defaults.in_progress_state.as_deref(),
        non_interactive,
    )?;
    print_project_status_help(ProjectStatusHelpTopic::HumanReviewState);
    let human_review_state = ask_optional_string(
        theme,
        "Status to set for review or blocked handoff (optional)",
        defaults.human_review_state.as_deref(),
        non_interactive,
    )?;
    print_project_status_help(ProjectStatusHelpTopic::DoneState);
    let done_state = ask_optional_string(
        theme,
        "Status to set when a closed issue is reconciled (optional)",
        defaults.done_state.as_deref(),
        non_interactive,
    )?;
    Ok(ProjectStatusConfig {
        active_states,
        terminal_states,
        claimable_states,
        in_progress_state,
        human_review_state,
        done_state,
    })
}

fn collect_non_interactive_project_status_config() -> ProjectStatusConfig {
    let defaults = canonical_project_status_config();
    ProjectStatusConfig {
        active_states: parse_list_env("KAIRASTRA_ACTIVE_STATES")
            .unwrap_or_else(|| defaults.active_states.clone()),
        terminal_states: parse_list_env("KAIRASTRA_TERMINAL_STATES")
            .unwrap_or_else(|| defaults.terminal_states.clone()),
        claimable_states: parse_list_env("KAIRASTRA_CLAIMABLE_STATES")
            .unwrap_or_else(|| defaults.claimable_states.clone()),
        in_progress_state: parse_optional_env("KAIRASTRA_IN_PROGRESS_STATE")
            .unwrap_or_else(|| defaults.in_progress_state.clone()),
        human_review_state: parse_optional_env("KAIRASTRA_HUMAN_REVIEW_STATE")
            .unwrap_or_else(|| defaults.human_review_state.clone()),
        done_state: parse_optional_env("KAIRASTRA_DONE_STATE")
            .unwrap_or_else(|| defaults.done_state.clone()),
    }
}

fn confirm_project_normalization(
    theme: &ColorfulTheme,
    project_owner: &str,
    project_number: &str,
) -> Result<()> {
    let token = status_normalization_confirmation_token(project_owner, project_number);
    println!();
    println!("Normalize GitHub Project Status field?");
    println!(
        "This will update the Status field on GitHub Project {}#{} to Kairastra's default options.",
        project_owner, project_number
    );
    println!(
        "Status options that are not in the target set will be removed from the field definition."
    );
    println!("Kairastra cannot undo this change.");
    let confirmation = ask_string(
        theme,
        &format!("To continue, type: {token}"),
        String::new(),
        false,
        true,
    )?;
    if confirmation != token {
        return Err(anyhow!(
            "project status normalization confirmation did not match"
        ));
    }
    Ok(())
}

fn collect_project_status_config(
    theme: &ColorfulTheme,
    non_interactive: bool,
    overview: Option<&ProjectStatusOverview>,
    github_owner: &str,
    github_project_owner: &str,
    github_project_number: &str,
) -> Result<(ProjectStatusConfig, bool)> {
    if non_interactive {
        return Ok((collect_non_interactive_project_status_config(), false));
    }

    if let Some(overview) = overview {
        let block_reason = project_status_overview_block_reason(overview);
        let normalize_label = if let Some(reason) = block_reason.as_ref() {
            format!("Normalize Project to Kairastra statuses (unavailable: {reason})")
        } else {
            "Normalize Project to Kairastra statuses".to_string()
        };
        print_project_status_help(ProjectStatusHelpTopic::Handling);
        let choice = Select::with_theme(theme)
            .with_prompt("Project status handling")
            .items(&[
                "Keep existing Project statuses (recommended)".to_string(),
                normalize_label,
            ])
            .default(0)
            .interact()?;
        if choice == 1 {
            if let Some(reason) = block_reason {
                return Err(anyhow!(
                    "{reason}. Kairastra will not rewrite a live Project without an explicit migration feature."
                ));
            }
            let project_owner = if github_project_owner.trim().is_empty() {
                github_owner
            } else {
                github_project_owner
            };
            confirm_project_normalization(theme, project_owner, github_project_number)?;
            return Ok((canonical_project_status_config(), true));
        }
        return Ok((
            collect_existing_project_status_config(theme, overview)?,
            false,
        ));
    }

    Ok((collect_manual_project_status_config(theme, false)?, false))
}

fn normalize_project_statuses(layout: &SetupLayout, values: &SetupValues) -> Result<()> {
    let script = layout.repo_root.join("scripts/bootstrap_github_project.py");
    if !script.is_file() {
        return Err(anyhow!(
            "status normalization helper not found at {}",
            script.display()
        ));
    }

    let project_owner = if values.github_project_owner.trim().is_empty() {
        values.github_owner.as_str()
    } else {
        values.github_project_owner.as_str()
    };
    let confirmation_token =
        status_normalization_confirmation_token(project_owner, &values.github_project_number);

    let output = Command::new("python3")
        .arg(&script)
        .arg("--owner")
        .arg(&values.github_owner)
        .arg("--repo")
        .arg(&values.github_repo)
        .arg("--project-owner")
        .arg(project_owner)
        .arg("--project-number")
        .arg(&values.github_project_number)
        .arg("--status-mode")
        .arg("normalize")
        .arg("--skip-labels")
        .arg("--skip-priority-field")
        .arg("--confirm-normalize-token")
        .arg(&confirmation_token)
        .output()
        .with_context(|| format!("failed to run {}", script.display()))?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr).trim().to_string();
        let stdout = String::from_utf8_lossy(&output.stdout).trim().to_string();
        return Err(anyhow!(
            "project status normalization failed: {}",
            if stderr.is_empty() { stdout } else { stderr }
        ));
    }

    Ok(())
}

fn write_text_file(path: &Path, content: &str, non_interactive: bool) -> Result<()> {
    if let Some(parent) = path.parent() {
        if !parent.as_os_str().is_empty() {
            fs::create_dir_all(parent)
                .with_context(|| format!("failed to create {}", parent.display()))?;
        }
    }

    let should_write = if path.exists() && !non_interactive {
        if is_replaceable_bootstrap_file(path)? {
            true
        } else {
            Confirm::with_theme(&ColorfulTheme::default())
                .with_prompt(format!("Overwrite {}?", path.display()))
                .default(false)
                .interact()?
        }
    } else {
        true
    };

    if should_write {
        fs::write(path, content).with_context(|| format!("failed to write {}", path.display()))?;
    }

    Ok(())
}

fn is_replaceable_bootstrap_file(path: &Path) -> Result<bool> {
    let existing = fs::read_to_string(path)
        .with_context(|| format!("failed to read existing {}", path.display()))?;

    Ok(existing == REMOTE_DOCKER_WORKFLOW_PLACEHOLDER
        || existing.starts_with(REMOTE_DOCKER_ENV_BOOTSTRAP_PREFIX))
}

fn render_yaml_list(values: &[String], indent: usize) -> String {
    if values.is_empty() {
        return format!("{}[]\n", " ".repeat(indent));
    }
    let prefix = " ".repeat(indent);
    values
        .iter()
        .map(|value| format!("{prefix}- {}\n", render_yaml_scalar(value)))
        .collect::<String>()
}

fn render_optional_yaml_value(value: Option<&str>) -> String {
    match value {
        Some(value) => render_yaml_scalar(value),
        None => "null".to_string(),
    }
}

fn render_yaml_scalar(value: &str) -> String {
    serde_json::to_string(value).expect("YAML scalar serialization should succeed")
}

fn render_workflow(mode: DeployMode, values: &SetupValues) -> String {
    let assignee_line = if values.assignee_login.trim().is_empty() {
        String::new()
    } else {
        "  assignee_login: $KAIRASTRA_AGENT_ASSIGNEE\n".to_string()
    };
    let provider_sections = values
        .provider_configs
        .iter()
        .map(providers::render_workflow_provider_section)
        .collect::<Vec<_>>()
        .join("\n");
    if mode == DeployMode::Docker {
        let tracker_block = match values.tracker_mode {
            GitHubMode::ProjectsV2 => {
                format!(
                    r#"tracker:
  kind: github
  mode: projects_v2
  api_key: $GITHUB_TOKEN
  owner: $KAIRASTRA_GITHUB_OWNER
  repo: $KAIRASTRA_GITHUB_REPO
  project_owner: $KAIRASTRA_GITHUB_PROJECT_OWNER
  project_v2_number: $KAIRASTRA_GITHUB_PROJECT_NUMBER
  project_url: $KAIRASTRA_GITHUB_PROJECT_URL
  status_source:
    type: project_field
    name: Status
  priority_source:
    type: project_field
    name: Priority
  active_states:
{active_states}  terminal_states:
{terminal_states}  claimable_states:
{claimable_states}  in_progress_state: {in_progress_state}
  human_review_state: {human_review_state}
  done_state: {done_state}"#,
                    active_states = render_yaml_list(&values.project_status.active_states, 4),
                    terminal_states = render_yaml_list(&values.project_status.terminal_states, 4),
                    claimable_states = render_yaml_list(&values.project_status.claimable_states, 4),
                    in_progress_state = render_optional_yaml_value(
                        values.project_status.in_progress_state.as_deref()
                    ),
                    human_review_state = render_optional_yaml_value(
                        values.project_status.human_review_state.as_deref()
                    ),
                    done_state =
                        render_optional_yaml_value(values.project_status.done_state.as_deref()),
                )
            }
            GitHubMode::IssuesOnly => r#"tracker:
  kind: github
  mode: issues_only
  api_key: $GITHUB_TOKEN
  owner: $KAIRASTRA_GITHUB_OWNER
  repo: $KAIRASTRA_GITHUB_REPO
  status_source:
    type: github_state
  active_states:
    - Open
  terminal_states:
    - Closed"#
                .to_string(),
        };

        return format!(
            r#"---
{tracker_block}
workspace:
  root: $KAIRASTRA_WORKSPACE_ROOT
agent:
  provider: {provider}
  max_concurrent_agents: {max_concurrent_agents}
  max_turns: {max_turns}
{assignee_line}providers:
{provider_sections}
---

Docker deployment config.

Workspace prompts and repo-local hooks come from `<repo>/WORKFLOW.md` inside each workspace when
present. When a repo does not define that file, Kairastra uses its built-in default workspace
workflow. Provider-specific Codex skills are synced into the agent home and do not live in the
managed repo checkout.
"#,
            tracker_block = tracker_block,
            provider = values.provider,
            max_concurrent_agents = values.max_concurrent_agents,
            max_turns = values.max_turns,
            assignee_line = assignee_line,
            provider_sections = provider_sections,
        );
    }

    let mut support_dirs = Vec::new();
    for config in &values.provider_configs {
        for dir in providers::repo_support_dirs(providers::setup_provider_id(config))
            .unwrap_or(&[".github"])
        {
            if !support_dirs.iter().any(|existing| existing == dir) {
                support_dirs.push(*dir);
            }
        }
    }
    let support_dirs = support_dirs.join(" ");
    let tracker_block = match values.tracker_mode {
        GitHubMode::ProjectsV2 => {
            format!(
                r#"tracker:
  kind: github
  mode: projects_v2
  api_key: $GITHUB_TOKEN
  owner: $KAIRASTRA_GITHUB_OWNER
  repo: $KAIRASTRA_GITHUB_REPO
  project_owner: $KAIRASTRA_GITHUB_PROJECT_OWNER
  project_v2_number: $KAIRASTRA_GITHUB_PROJECT_NUMBER
  project_url: $KAIRASTRA_GITHUB_PROJECT_URL
  status_source:
    type: project_field
    name: Status
  priority_source:
    type: project_field
    name: Priority
  active_states:
{active_states}  terminal_states:
{terminal_states}  claimable_states:
{claimable_states}  in_progress_state: {in_progress_state}
  human_review_state: {human_review_state}
  done_state: {done_state}"#,
                active_states = render_yaml_list(&values.project_status.active_states, 4),
                terminal_states = render_yaml_list(&values.project_status.terminal_states, 4),
                claimable_states = render_yaml_list(&values.project_status.claimable_states, 4),
                in_progress_state =
                    render_optional_yaml_value(values.project_status.in_progress_state.as_deref()),
                human_review_state =
                    render_optional_yaml_value(values.project_status.human_review_state.as_deref()),
                done_state =
                    render_optional_yaml_value(values.project_status.done_state.as_deref()),
            )
        }
        GitHubMode::IssuesOnly => r#"tracker:
  kind: github
  mode: issues_only
  api_key: $GITHUB_TOKEN
  owner: $KAIRASTRA_GITHUB_OWNER
  repo: $KAIRASTRA_GITHUB_REPO
  status_source:
    type: github_state
  active_states:
    - Open
  terminal_states:
    - Closed"#
            .to_string(),
    };

    format!(
        r#"---
{tracker_block}
workspace:
  root: $KAIRASTRA_WORKSPACE_ROOT
hooks:
  after_create: |
    set -euo pipefail

    clone_with_auth() {{
      clone_url="$1"
      if [ -n "${{GITHUB_TOKEN:-}}" ] && printf '%s' "$clone_url" | grep -q '^https://github.com/'; then
        auth_header="$(printf 'x-access-token:%s' "$GITHUB_TOKEN" | base64 | tr -d '\n')"
        git -c http.extraheader="Authorization: Basic ${{auth_header}}" clone --depth 1 "$clone_url" .
        git config http.https://github.com/.extraheader "Authorization: Basic ${{auth_header}}"
      else
        git clone --depth 1 "$clone_url" .
      fi
    }}

    overlay_seed_repo() {{
      seed_repo="$1"
      if command -v rsync >/dev/null 2>&1; then
        rsync -a --delete --exclude '.git' "${{seed_repo}}/" ./
      else
        echo "rsync is required when overlaying KAIRASTRA_SEED_REPO on top of a remote clone." >&2
        exit 1
      fi
    }}

    github_https_url() {{
      remote_url="$1"
      case "$remote_url" in
        git@github.com:*)
          printf 'https://github.com/%s\n' "${{remote_url#git@github.com:}}"
          ;;
        ssh://git@github.com/*)
          printf 'https://github.com/%s\n' "${{remote_url#ssh://git@github.com/}}"
          ;;
        *)
          printf '%s\n' "$remote_url"
          ;;
      esac
    }}

    configure_github_auth() {{
      if [ -z "${{GITHUB_TOKEN:-}}" ]; then
        return 0
      fi

      origin_url="$(git config --get remote.origin.url || true)"
      normalized_origin_url="$(github_https_url "$origin_url")"
      if [ -n "$normalized_origin_url" ] && [ "$normalized_origin_url" != "$origin_url" ]; then
        git remote set-url origin "$normalized_origin_url"
      fi

      push_url="$(git config --get remote.origin.pushurl || true)"
      normalized_push_url="$(github_https_url "$push_url")"
      if [ -n "$normalized_push_url" ] && [ "$normalized_push_url" != "$push_url" ]; then
        git remote set-url --push origin "$normalized_push_url"
      fi

      auth_header="$(printf 'x-access-token:%s' "$GITHUB_TOKEN" | base64 | tr -d '\n')"
      git config http.https://github.com/.extraheader "Authorization: Basic ${{auth_header}}"
    }}

    restore_support_dir_from_seed() {{
      support_dir="$1"
      if [ -e "$support_dir" ]; then
        return 0
      fi
      if [ -n "${{KAIRASTRA_SEED_REPO:-}}" ] && [ -e "${{KAIRASTRA_SEED_REPO}}/$support_dir" ]; then
        cp -R "${{KAIRASTRA_SEED_REPO}}/$support_dir" "$support_dir"
      fi
    }}

    exclude_workspace_support_dir() {{
      support_dir="$1"
      exclude_path="$(git rev-parse --git-path info/exclude 2>/dev/null || true)"
      if [ -z "$exclude_path" ]; then
        return 0
      fi
      mkdir -p "$(dirname "$exclude_path")"
      touch "$exclude_path"
      entry="$support_dir/"
      if ! grep -Fqx "$entry" "$exclude_path" 2>/dev/null; then
        printf '%s\n' "$entry" >> "$exclude_path"
      fi
    }}

    prune_legacy_codex_workspace_support() {{
      if [ ! -e ".codex" ]; then
        return 0
      fi
      if git ls-files -- .codex 2>/dev/null | grep -q .; then
        return 0
      fi
      rm -rf .codex
    }}

    require_workspace_support_dirs() {{
      for support_dir in {support_dirs}; do
        restore_support_dir_from_seed "$support_dir"
        if [ ! -e "$support_dir" ]; then
          echo "Workspace bootstrap missing required repository support directory: $support_dir" >&2
          exit 1
        fi
        exclude_workspace_support_dir "$support_dir"
      done
    }}

    adopt_seed_repo_origin() {{
      if [ -z "${{KAIRASTRA_SEED_REPO:-}}" ] || [ ! -d "$KAIRASTRA_SEED_REPO/.git" ]; then
        return 0
      fi
      source_remote="$(git -C "$KAIRASTRA_SEED_REPO" config --get remote.origin.url || true)"
      current_remote="$(git config --get remote.origin.url || true)"
      if [ -n "$source_remote" ] && {{ [ "$current_remote" = "$KAIRASTRA_SEED_REPO" ] || [ -z "$current_remote" ]; }}; then
        git remote set-url origin "$source_remote"
      fi
    }}

    resolve_default_branch() {{
      if [ -n "${{KAIRASTRA_GIT_DEFAULT_BRANCH:-}}" ]; then
        printf '%s\n' "${{KAIRASTRA_GIT_DEFAULT_BRANCH}}"
        return 0
      fi

      remote_head="$(git symbolic-ref --quiet --short refs/remotes/origin/HEAD 2>/dev/null || true)"
      if [ -n "$remote_head" ]; then
        printf '%s\n' "${{remote_head#origin/}}"
        return 0
      fi

      remote_head="$(git remote show origin 2>/dev/null | sed -n 's/.*HEAD branch: //p' | head -n 1)"
      if [ -n "$remote_head" ]; then
        printf '%s\n' "$remote_head"
        return 0
      fi

      printf 'main\n'
    }}

    fetch_origin_branch() {{
      branch_name="$1"
      if [ -z "$branch_name" ] || [ "$branch_name" = "HEAD" ]; then
        return 0
      fi
      git fetch --quiet origin "refs/heads/$branch_name:refs/remotes/origin/$branch_name" || true
    }}

    ensure_default_branch_baseline() {{
      current_branch="$(git rev-parse --abbrev-ref HEAD 2>/dev/null || true)"
      default_branch="$(resolve_default_branch)"
      if [ -z "$default_branch" ]; then
        return 0
      fi

      fetch_origin_branch "$default_branch"
      if [ -n "$current_branch" ] && [ "$current_branch" != "$default_branch" ]; then
        fetch_origin_branch "$current_branch"
      fi

      is_shallow="$(git rev-parse --is-shallow-repository 2>/dev/null || printf 'false\n')"
      if [ "$is_shallow" = "true" ]; then
        if [ -n "$current_branch" ] && [ "$current_branch" != "$default_branch" ] && [ "$current_branch" != "HEAD" ]; then
          git fetch --quiet --unshallow origin \
            "refs/heads/$default_branch:refs/remotes/origin/$default_branch" \
            "refs/heads/$current_branch:refs/remotes/origin/$current_branch" \
            || true
        else
          git fetch --quiet --unshallow origin \
            "refs/heads/$default_branch:refs/remotes/origin/$default_branch" \
            || true
        fi
      fi

      if git merge-base "origin/$default_branch" HEAD >/dev/null 2>&1; then
        return 0
      fi

      if [ -n "$current_branch" ] && [ "$current_branch" != "HEAD" ]; then
        git fetch --quiet origin \
          "refs/heads/$current_branch:refs/remotes/origin/$current_branch" \
          "refs/heads/$default_branch:refs/remotes/origin/$default_branch" \
          || true
      else
        git fetch --quiet origin "refs/heads/$default_branch:refs/remotes/origin/$default_branch" || true
      fi
    }}

    if [ -n "${{KAIRASTRA_GIT_CLONE_URL:-}}" ]; then
      clone_with_auth "$KAIRASTRA_GIT_CLONE_URL"
      if [ -n "${{KAIRASTRA_SEED_REPO:-}}" ] && [ -d "$KAIRASTRA_SEED_REPO" ]; then
        overlay_seed_repo "$KAIRASTRA_SEED_REPO"
      fi
    elif [ -n "${{KAIRASTRA_SEED_REPO:-}}" ] && [ -d "$KAIRASTRA_SEED_REPO/.git" ]; then
      git clone "$KAIRASTRA_SEED_REPO" .
      adopt_seed_repo_origin
    else
      echo "Set KAIRASTRA_GIT_CLONE_URL, or point KAIRASTRA_SEED_REPO at a git checkout, before running Kairastra." >&2
      exit 1
    fi

    if [ -n "${{KAIRASTRA_GIT_PUSH_URL:-}}" ]; then
      git remote set-url --push origin "$KAIRASTRA_GIT_PUSH_URL"
    fi

    prune_legacy_codex_workspace_support
    require_workspace_support_dirs
    configure_github_auth
    ensure_default_branch_baseline

    git config user.name "${{KAIRASTRA_GIT_AUTHOR_NAME:-Kairastra}}"
    git config user.email "${{KAIRASTRA_GIT_AUTHOR_EMAIL:-kairastra@users.noreply.github.com}}"
  before_run: |
    set -euo pipefail

    git config --global --add safe.directory "$(pwd)"

    restore_support_dir_from_seed() {{
      support_dir="$1"
      if [ -e "$support_dir" ]; then
        return 0
      fi
      if [ -n "${{KAIRASTRA_SEED_REPO:-}}" ] && [ -e "${{KAIRASTRA_SEED_REPO}}/$support_dir" ]; then
        cp -R "${{KAIRASTRA_SEED_REPO}}/$support_dir" "$support_dir"
      fi
    }}

    exclude_workspace_support_dir() {{
      support_dir="$1"
      exclude_path="$(git rev-parse --git-path info/exclude 2>/dev/null || true)"
      if [ -z "$exclude_path" ]; then
        return 0
      fi
      mkdir -p "$(dirname "$exclude_path")"
      touch "$exclude_path"
      entry="$support_dir/"
      if ! grep -Fqx "$entry" "$exclude_path" 2>/dev/null; then
        printf '%s\n' "$entry" >> "$exclude_path"
      fi
    }}

    prune_legacy_codex_workspace_support() {{
      if [ ! -e ".codex" ]; then
        return 0
      fi
      if git ls-files -- .codex 2>/dev/null | grep -q .; then
        return 0
      fi
      rm -rf .codex
    }}

    require_workspace_support_dirs() {{
      for support_dir in {support_dirs}; do
        restore_support_dir_from_seed "$support_dir"
        if [ ! -e "$support_dir" ]; then
          echo "Workspace bootstrap missing required repository support directory: $support_dir" >&2
          exit 1
        fi
        exclude_workspace_support_dir "$support_dir"
      done
    }}

    github_https_url() {{
      remote_url="$1"
      case "$remote_url" in
        git@github.com:*)
          printf 'https://github.com/%s\n' "${{remote_url#git@github.com:}}"
          ;;
        ssh://git@github.com/*)
          printf 'https://github.com/%s\n' "${{remote_url#ssh://git@github.com/}}"
          ;;
        *)
          printf '%s\n' "$remote_url"
          ;;
      esac
    }}

    configure_github_auth() {{
      if [ -z "${{GITHUB_TOKEN:-}}" ]; then
        return 0
      fi

      origin_url="$(git config --get remote.origin.url || true)"
      normalized_origin_url="$(github_https_url "$origin_url")"
      if [ -n "$normalized_origin_url" ] && [ "$normalized_origin_url" != "$origin_url" ]; then
        git remote set-url origin "$normalized_origin_url"
      fi

      push_url="$(git config --get remote.origin.pushurl || true)"
      normalized_push_url="$(github_https_url "$push_url")"
      if [ -n "$normalized_push_url" ] && [ "$normalized_push_url" != "$push_url" ]; then
        git remote set-url --push origin "$normalized_push_url"
      fi

      auth_header="$(printf 'x-access-token:%s' "$GITHUB_TOKEN" | base64 | tr -d '\n')"
      git config http.https://github.com/.extraheader "Authorization: Basic ${{auth_header}}"
    }}

    adopt_seed_repo_origin() {{
      if [ -z "${{KAIRASTRA_SEED_REPO:-}}" ] || [ ! -d "$KAIRASTRA_SEED_REPO/.git" ]; then
        return 0
      fi
      source_remote="$(git -C "$KAIRASTRA_SEED_REPO" config --get remote.origin.url || true)"
      current_remote="$(git config --get remote.origin.url || true)"
      if [ -n "$source_remote" ] && {{ [ "$current_remote" = "$KAIRASTRA_SEED_REPO" ] || [ -z "$current_remote" ]; }}; then
        git remote set-url origin "$source_remote"
      fi
    }}

    resolve_default_branch() {{
      if [ -n "${{KAIRASTRA_GIT_DEFAULT_BRANCH:-}}" ]; then
        printf '%s\n' "${{KAIRASTRA_GIT_DEFAULT_BRANCH}}"
        return 0
      fi

      remote_head="$(git symbolic-ref --quiet --short refs/remotes/origin/HEAD 2>/dev/null || true)"
      if [ -n "$remote_head" ]; then
        printf '%s\n' "${{remote_head#origin/}}"
        return 0
      fi

      remote_head="$(git remote show origin 2>/dev/null | sed -n 's/.*HEAD branch: //p' | head -n 1)"
      if [ -n "$remote_head" ]; then
        printf '%s\n' "$remote_head"
        return 0
      fi

      printf 'main\n'
    }}

    fetch_origin_branch() {{
      branch_name="$1"
      if [ -z "$branch_name" ] || [ "$branch_name" = "HEAD" ]; then
        return 0
      fi
      git fetch --quiet origin "refs/heads/$branch_name:refs/remotes/origin/$branch_name" || true
    }}

    ensure_default_branch_baseline() {{
      current_branch="$(git rev-parse --abbrev-ref HEAD 2>/dev/null || true)"
      default_branch="$(resolve_default_branch)"
      if [ -z "$default_branch" ]; then
        return 0
      fi

      fetch_origin_branch "$default_branch"
      if [ -n "$current_branch" ] && [ "$current_branch" != "$default_branch" ]; then
        fetch_origin_branch "$current_branch"
      fi

      is_shallow="$(git rev-parse --is-shallow-repository 2>/dev/null || printf 'false\n')"
      if [ "$is_shallow" = "true" ]; then
        if [ -n "$current_branch" ] && [ "$current_branch" != "$default_branch" ] && [ "$current_branch" != "HEAD" ]; then
          git fetch --quiet --unshallow origin \
            "refs/heads/$default_branch:refs/remotes/origin/$default_branch" \
            "refs/heads/$current_branch:refs/remotes/origin/$current_branch" \
            || true
        else
          git fetch --quiet --unshallow origin \
            "refs/heads/$default_branch:refs/remotes/origin/$default_branch" \
            || true
        fi
      fi

      if git merge-base "origin/$default_branch" HEAD >/dev/null 2>&1; then
        return 0
      fi

      if [ -n "$current_branch" ] && [ "$current_branch" != "HEAD" ]; then
        git fetch --quiet origin \
          "refs/heads/$current_branch:refs/remotes/origin/$current_branch" \
          "refs/heads/$default_branch:refs/remotes/origin/$default_branch" \
          || true
      else
        git fetch --quiet origin "refs/heads/$default_branch:refs/remotes/origin/$default_branch" || true
      fi
    }}

    prune_legacy_codex_workspace_support
    require_workspace_support_dirs
    adopt_seed_repo_origin

    if [ -n "${{KAIRASTRA_GIT_PUSH_URL:-}}" ]; then
      git remote set-url --push origin "$KAIRASTRA_GIT_PUSH_URL"
    fi

    configure_github_auth
    ensure_default_branch_baseline

    git config user.name "${{KAIRASTRA_GIT_AUTHOR_NAME:-Kairastra}}"
    git config user.email "${{KAIRASTRA_GIT_AUTHOR_EMAIL:-kairastra@users.noreply.github.com}}"
agent:
  provider: {provider}
  max_concurrent_agents: {max_concurrent_agents}
  max_turns: {max_turns}
{assignee_line}providers:
{provider_sections}
---

You are working on GitHub issue `{{{{ issue.identifier }}}}`.

{{% if tracker.dashboard_url %}}
Dashboard: {{{{ tracker.dashboard_url }}}}
{{% endif %}}
Title: {{{{ issue.title }}}}
URL: {{{{ issue.url }}}}

Description:
{{% if issue.description %}}
{{{{ issue.description }}}}
{{% else %}}
No description provided.
{{% endif %}}
"#,
        tracker_block = tracker_block,
        provider = values.provider,
        max_concurrent_agents = values.max_concurrent_agents,
        max_turns = values.max_turns,
        assignee_line = assignee_line,
        provider_sections = provider_sections,
        support_dirs = support_dirs
    )
}

fn render_project_env_lines(values: &SetupValues) -> String {
    if values.tracker_mode != GitHubMode::ProjectsV2 {
        return String::new();
    }

    format!(
        "KAIRASTRA_GITHUB_PROJECT_OWNER={}\nKAIRASTRA_GITHUB_PROJECT_NUMBER={}\nKAIRASTRA_GITHUB_PROJECT_URL={}\n",
        values.github_project_owner, values.github_project_number, values.github_project_url
    )
}

fn render_env_file(mode: DeployMode, values: &SetupValues, workflow_path: &Path) -> String {
    let project_env_lines = render_project_env_lines(values);
    let provider_env = values
        .provider_configs
        .iter()
        .map(|config| providers::render_env_provider_section(mode, config))
        .filter(|section| !section.trim().is_empty())
        .collect::<Vec<_>>()
        .join("\n");
    match mode {
        DeployMode::Native => format!(
            r#"# Generated by `kairastra setup`
KAIRASTRA_DEPLOY_MODE=native
GITHUB_TOKEN={github_token}
ANTHROPIC_API_KEY={anthropic_api_key}
GEMINI_API_KEY={gemini_api_key}
OPENAI_API_KEY={openai_api_key}
WORKFLOW_PATH={workflow_path}
KAIRASTRA_WORKSPACE_ROOT={workspace_root}
KAIRASTRA_GITHUB_OWNER={github_owner}
KAIRASTRA_GITHUB_REPO={github_repo}
{project_env_lines}KAIRASTRA_GIT_CLONE_URL={git_clone_url}
KAIRASTRA_SEED_REPO={seed_repo}
KAIRASTRA_AGENT_ASSIGNEE={assignee_login}
{provider_env}
RUST_LOG={rust_log}
"#,
            github_token = values.github_token,
            anthropic_api_key = values.anthropic_api_key,
            gemini_api_key = values.gemini_api_key,
            openai_api_key = values.openai_api_key,
            workflow_path = absolute_display_path(workflow_path),
            workspace_root = values.workspace_root,
            github_owner = values.github_owner,
            github_repo = values.github_repo,
            project_env_lines = project_env_lines,
            git_clone_url = values.git_clone_url,
            seed_repo = values.seed_repo,
            assignee_login = values.assignee_login,
            provider_env = provider_env,
            rust_log = values.rust_log,
        ),
        DeployMode::Docker => format!(
            r#"# Generated by `kairastra setup`
KAIRASTRA_DEPLOY_MODE=docker
GITHUB_TOKEN={github_token}
ANTHROPIC_API_KEY={anthropic_api_key}
GEMINI_API_KEY={gemini_api_key}
OPENAI_API_KEY={openai_api_key}
KAIRASTRA_WORKSPACE_ROOT={workspace_root}
RUST_LOG={rust_log}
KAIRASTRA_GITHUB_OWNER={github_owner}
KAIRASTRA_GITHUB_REPO={github_repo}
{project_env_lines}KAIRASTRA_GIT_CLONE_URL={git_clone_url}
KAIRASTRA_AGENT_ASSIGNEE={assignee_login}
{provider_env}
"#,
            github_token = values.github_token,
            anthropic_api_key = values.anthropic_api_key,
            gemini_api_key = values.gemini_api_key,
            openai_api_key = values.openai_api_key,
            workspace_root = values.workspace_root,
            rust_log = values.rust_log,
            github_owner = values.github_owner,
            github_repo = values.github_repo,
            project_env_lines = project_env_lines,
            git_clone_url = values.git_clone_url,
            assignee_login = values.assignee_login,
            provider_env = provider_env,
        ),
    }
}

fn render_systemd_unit(values: &SetupValues, workflow_path: &Path, env_file: &Path) -> String {
    format!(
        r#"[Unit]
Description=Kairastra Rust orchestrator
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
EnvironmentFile={}
WorkingDirectory={}
ExecStart={} run {}
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
"#,
        absolute_display_path(env_file),
        std::env::current_dir()
            .map(|path| path.display().to_string())
            .unwrap_or_else(|_| ".".to_string()),
        values.binary_path,
        absolute_display_path(workflow_path)
    )
}

fn absolute_display_path(path: &Path) -> String {
    fs::canonicalize(path)
        .unwrap_or_else(|_| path.to_path_buf())
        .display()
        .to_string()
}

#[cfg(test)]
mod tests {
    use super::{
        render_env_file, render_systemd_unit, render_workflow, write_text_file, SetupValues,
        REMOTE_DOCKER_ENV_BOOTSTRAP_PREFIX, REMOTE_DOCKER_WORKFLOW_PLACEHOLDER,
    };
    use crate::config::GitHubMode;
    use crate::deploy::DeployMode;
    use crate::providers::claude::setup::ClaudeSetupConfig;
    use crate::providers::codex::setup::CodexSetupConfig;
    use crate::providers::gemini::setup::GeminiSetupConfig;
    use crate::providers::ProviderSetupConfig;
    use std::fs;
    use std::path::Path;
    use std::sync::Mutex;
    use tempfile::tempdir;

    static ENV_LOCK: Mutex<()> = Mutex::new(());

    fn sample_values() -> SetupValues {
        SetupValues {
            tracker_mode: GitHubMode::ProjectsV2,
            project_status: super::canonical_project_status_config(),
            normalize_project_statuses: false,
            provider: "codex".to_string(),
            provider_configs: vec![
                ProviderSetupConfig::Codex(CodexSetupConfig {
                    auth_mode: crate::auth::AuthMode::Subscription,
                    model: "gpt-5.4".to_string(),
                    reasoning_effort: "high".to_string(),
                    fast: Some(true),
                }),
                ProviderSetupConfig::Claude(ClaudeSetupConfig {
                    auth_mode: crate::auth::AuthMode::ApiKey,
                    model: "sonnet".to_string(),
                    reasoning_effort: "high".to_string(),
                }),
                ProviderSetupConfig::Gemini(GeminiSetupConfig {
                    auth_mode: crate::auth::AuthMode::Subscription,
                    model: "gemini-2.5-pro".to_string(),
                    approval_mode: "yolo".to_string(),
                }),
            ],
            github_owner: "openai".to_string(),
            github_repo: "kairastra".to_string(),
            github_project_owner: "dbachko".to_string(),
            github_project_number: "7".to_string(),
            github_project_url: "https://github.com/users/dbachko/projects/7".to_string(),
            workspace_root: "/workspaces".to_string(),
            seed_repo: "/seed".to_string(),
            git_clone_url: "https://github.com/openai/kairastra.git".to_string(),
            assignee_login: "codex-bot".to_string(),
            max_concurrent_agents: "4".to_string(),
            max_turns: "20".to_string(),
            github_token: String::new(),
            anthropic_api_key: String::new(),
            gemini_api_key: String::new(),
            openai_api_key: String::new(),
            rust_log: "info".to_string(),
            binary_path: "/usr/local/bin/kairastra".to_string(),
        }
    }

    #[test]
    fn workflow_template_uses_env_placeholders() {
        let rendered = render_workflow(DeployMode::Native, &sample_values());
        assert!(rendered.contains("owner: $KAIRASTRA_GITHUB_OWNER"));
        assert!(rendered.contains("project_owner: $KAIRASTRA_GITHUB_PROJECT_OWNER"));
        assert!(rendered.contains("provider: codex"));
        assert!(rendered.contains("assignee_login: $KAIRASTRA_AGENT_ASSIGNEE"));
        assert!(rendered.contains("providers:"));
        assert!(rendered.contains("  codex:"));
        assert!(rendered.contains("  claude:"));
        assert!(rendered.contains("  gemini:"));
        assert!(rendered.contains("model: $KAIRASTRA_CODEX_MODEL"));
        assert!(rendered.contains("model: $KAIRASTRA_CLAUDE_MODEL"));
        assert!(rendered.contains("model: $KAIRASTRA_GEMINI_MODEL"));
        assert!(rendered.contains("reasoning_effort: $KAIRASTRA_CODEX_REASONING_EFFORT"));
        assert!(rendered.contains("reasoning_effort: $KAIRASTRA_CLAUDE_REASONING_EFFORT"));
        assert!(rendered.contains("approval_mode: $KAIRASTRA_GEMINI_APPROVAL_MODE"));
        assert!(rendered.contains("fast: $KAIRASTRA_CODEX_FAST"));
        assert!(rendered.contains("for support_dir in .github; do"));
        assert!(!rendered.contains("for support_dir in .codex .github; do"));
        assert!(rendered.contains("git rev-parse --git-path info/exclude"));
        assert!(rendered.contains("entry=\"$support_dir/\""));
        assert!(rendered.contains("prune_legacy_codex_workspace_support"));
        assert!(rendered.contains("git ls-files -- .codex"));
        assert!(
            rendered.contains("Workspace bootstrap missing required repository support directory")
        );
        assert!(rendered.contains("git -C \"$KAIRASTRA_SEED_REPO\" config --get remote.origin.url"));
        assert!(rendered.contains("adopt_seed_repo_origin"));
        assert!(rendered.contains("git remote set-url --push origin \"$KAIRASTRA_GIT_PUSH_URL\""));
        assert!(rendered.contains("git config --get remote.origin.pushurl || true"));
        assert!(rendered.contains("http.https://github.com/.extraheader"));
        assert!(rendered.contains("resolve_default_branch()"));
        assert!(rendered.contains("fetch_origin_branch()"));
        assert!(rendered.contains("fetch_origin_branch \"$default_branch\""));
        assert!(rendered.contains("fetch_origin_branch \"$current_branch\""));
        assert!(rendered.contains("ensure_default_branch_baseline()"));
        assert!(rendered.contains("git fetch --quiet --unshallow origin \\"));
        assert!(rendered.contains("before_run: |"));
        assert!(
            rendered.contains("current_remote=\"$(git config --get remote.origin.url || true)\"")
        );
        assert!(rendered.contains(r#"  in_progress_state: "In Progress""#));
        assert!(rendered.contains(r#"  human_review_state: "Human Review""#));
        assert!(rendered.contains(r#"  done_state: "Done""#));
    }

    #[test]
    fn claude_default_workflow_still_includes_all_provider_blocks() {
        let mut values = sample_values();
        values.provider = "claude".to_string();

        let rendered = render_workflow(DeployMode::Native, &values);
        assert!(rendered.contains("provider: claude"));
        assert!(rendered.contains("for support_dir in .github; do"));
        assert!(rendered.contains("  codex:"));
        assert!(rendered.contains("  claude:"));
        assert!(rendered.contains("  gemini:"));
        assert!(rendered.contains("model: $KAIRASTRA_CLAUDE_MODEL"));
        assert!(rendered.contains("reasoning_effort: $KAIRASTRA_CLAUDE_REASONING_EFFORT"));
    }

    #[test]
    fn docker_workflow_describes_repo_owned_workspace_behavior() {
        let rendered = render_workflow(DeployMode::Docker, &sample_values());
        assert!(rendered.contains("Workspace prompts and repo-local hooks come from"));
        assert!(rendered.contains("Codex skills are synced into the agent home"));
        assert!(!rendered.contains("before_run: |"));
    }

    #[test]
    fn docker_env_omits_removed_host_bind_keys() {
        let rendered = render_env_file(
            DeployMode::Docker,
            &sample_values(),
            Path::new("WORKFLOW.md"),
        );
        assert!(!rendered.contains("WORKFLOW_FILE="));
        assert!(!rendered.contains("SEED_REPO_PATH="));
        assert!(rendered.contains("KAIRASTRA_GITHUB_PROJECT_OWNER=dbachko"));
        assert!(rendered.contains("CODEX_AUTH_MODE=subscription"));
        assert!(rendered.contains("KAIRASTRA_CODEX_MODEL=gpt-5.4"));
        assert!(rendered.contains("KAIRASTRA_CODEX_REASONING_EFFORT=high"));
        assert!(rendered.contains("KAIRASTRA_CODEX_FAST=true"));
        assert!(rendered.contains("CLAUDE_AUTH_MODE=api_key"));
        assert!(rendered.contains("KAIRASTRA_CLAUDE_MODEL=sonnet"));
        assert!(rendered.contains("KAIRASTRA_CLAUDE_REASONING_EFFORT=high"));
        assert!(rendered.contains("GEMINI_AUTH_MODE=subscription"));
        assert!(rendered.contains("KAIRASTRA_GEMINI_MODEL=gemini-2.5-pro"));
        assert!(rendered.contains("KAIRASTRA_GEMINI_APPROVAL_MODE=yolo"));
    }

    #[test]
    fn systemd_unit_runs_run_subcommand() {
        let rendered = render_systemd_unit(
            &sample_values(),
            Path::new("WORKFLOW.md"),
            Path::new("kairastra.env"),
        );
        assert!(rendered.contains("ExecStart=/usr/local/bin/kairastra run"));
    }

    #[test]
    fn parses_project_url_for_owner_and_number() {
        let parsed =
            super::parse_project_url("https://github.com/users/openai/projects/7").unwrap();
        assert_eq!(parsed.owner, "openai");
        assert_eq!(parsed.project_number, "7");
        assert_eq!(parsed.owner_kind, super::ProjectOwnerKind::User);
    }

    #[test]
    fn parses_org_project_url_with_extra_path() {
        let parsed =
            super::parse_project_url("https://github.com/orgs/acme/projects/12/views/1").unwrap();
        assert_eq!(parsed.owner, "acme");
        assert_eq!(parsed.project_number, "12");
        assert_eq!(parsed.owner_kind, super::ProjectOwnerKind::Organization);
    }

    #[test]
    fn rejects_unrecognized_project_url() {
        assert!(super::parse_project_url("https://github.com/openai/kairastra").is_none());
    }

    #[test]
    fn parses_repo_input_from_url() {
        let parsed = super::parse_repo_input("https://github.com/openai/kairastra").unwrap();
        assert_eq!(parsed.owner.as_deref(), Some("openai"));
        assert_eq!(parsed.repo, "kairastra");
    }

    #[test]
    fn default_clone_url_prefers_selected_target_repo() {
        assert_eq!(
            super::default_target_clone_url("", "acme", "target-repo"),
            "https://github.com/acme/target-repo.git"
        );
        assert_eq!(
            super::default_target_clone_url("/tmp/bootstrap-source-repo", "acme", "target-repo"),
            "https://github.com/acme/target-repo.git"
        );
        assert_eq!(
            super::default_target_clone_url(
                "https://github.com/acme/bootstrap-source.git",
                "acme",
                "target-repo"
            ),
            "https://github.com/acme/target-repo.git"
        );
        assert_eq!(
            super::default_target_clone_url(
                "git@github.com:acme/target-repo.git",
                "acme",
                "target-repo"
            ),
            "git@github.com:acme/target-repo.git"
        );
    }

    #[test]
    fn detects_rust_subdir_layout() {
        let dir = tempdir().unwrap();
        let rust_dir = dir.path().join("rust");
        fs::create_dir_all(&rust_dir).unwrap();
        fs::write(rust_dir.join("Cargo.toml"), "").unwrap();
        fs::write(rust_dir.join("compose.yml"), "").unwrap();

        let from_root = super::detect_layout(dir.path());
        assert_eq!(from_root.repo_root, dir.path());
        assert_eq!(from_root.rust_dir, rust_dir);

        let from_rust = super::detect_layout(&rust_dir);
        assert_eq!(from_rust.repo_root, dir.path());
        assert_eq!(from_rust.rust_dir, rust_dir);
    }

    #[test]
    fn workflow_path_defaults_to_workflow_md_even_when_existing() {
        let dir = tempdir().unwrap();
        fs::write(dir.path().join("WORKFLOW.md"), "existing").unwrap();

        let layout = super::detect_layout(dir.path());
        let path = super::resolve_workflow_path(&layout, None);

        assert_eq!(path, dir.path().join("WORKFLOW.md"));
    }

    #[test]
    fn issues_only_workflow_uses_repo_first_defaults() {
        let mut values = sample_values();
        values.tracker_mode = GitHubMode::IssuesOnly;

        let rendered = render_workflow(DeployMode::Native, &values);
        assert!(rendered.contains("mode: issues_only"));
        assert!(rendered.contains("type: github_state"));
        assert!(rendered.contains("- Open"));
        assert!(!rendered.contains("project_v2_number"));
        assert!(!rendered.contains("project_owner"));
        assert!(!rendered.contains("type: project_field"));
    }

    #[test]
    fn issues_only_env_omits_project_specific_values() {
        let mut values = sample_values();
        values.tracker_mode = GitHubMode::IssuesOnly;

        let rendered = render_env_file(DeployMode::Native, &values, Path::new("WORKFLOW.md"));
        assert!(rendered.contains("KAIRASTRA_GITHUB_OWNER=openai"));
        assert!(rendered.contains("KAIRASTRA_GITHUB_REPO=kairastra"));
        assert!(!rendered.contains("KAIRASTRA_GITHUB_PROJECT_OWNER"));
        assert!(!rendered.contains("KAIRASTRA_GITHUB_PROJECT_NUMBER"));
        assert!(!rendered.contains("KAIRASTRA_GITHUB_PROJECT_URL"));
    }

    #[test]
    fn workflow_quotes_custom_status_names() {
        let mut values = sample_values();
        values.project_status.active_states = vec!["Ready: Waiting".to_string()];
        values.project_status.terminal_states = vec!["Done / Shipped".to_string()];
        values.project_status.claimable_states = vec!["Ready: Waiting".to_string()];
        values.project_status.in_progress_state = Some("Doing: Active".to_string());
        values.project_status.human_review_state = Some("Needs Review".to_string());
        values.project_status.done_state = None;

        let rendered = render_workflow(DeployMode::Native, &values);
        assert!(rendered.contains(r#"- "Ready: Waiting""#));
        assert!(rendered.contains(r#"- "Done / Shipped""#));
        assert!(rendered.contains(r#"  in_progress_state: "Doing: Active""#));
        assert!(rendered.contains(r#"  human_review_state: "Needs Review""#));
        assert!(rendered.contains("  done_state: null"));
    }

    #[test]
    fn resolve_github_token_accepts_gh_token_fallback() {
        let _guard = ENV_LOCK.lock().unwrap();
        std::env::remove_var("GITHUB_TOKEN");
        std::env::set_var("GH_TOKEN", "gh-token-123");

        let token = super::resolve_github_token(
            &dialoguer::theme::ColorfulTheme::default(),
            true,
            super::github_token_help_context(GitHubMode::IssuesOnly, None),
        )
        .unwrap();

        assert_eq!(token, "gh-token-123");

        std::env::remove_var("GH_TOKEN");
    }

    #[test]
    fn resolve_github_token_requires_non_interactive_secret() {
        let _guard = ENV_LOCK.lock().unwrap();
        std::env::remove_var("GITHUB_TOKEN");
        std::env::remove_var("GH_TOKEN");

        let error = super::resolve_github_token(
            &dialoguer::theme::ColorfulTheme::default(),
            true,
            super::github_token_help_context(GitHubMode::ProjectsV2, None),
        )
        .unwrap_err()
        .to_string();

        assert!(error.contains("Set GITHUB_TOKEN or GH_TOKEN before running setup"));
        assert!(error.contains("https://github.com/settings/tokens"));
        assert!(error.contains("https://github.com/settings/tokens/new"));
    }

    #[test]
    fn github_token_help_mentions_classic_pat_for_user_owned_projects_v2() {
        let parsed =
            super::parse_project_url("https://github.com/users/dbachko/projects/7").unwrap();
        let lines = super::github_token_help_lines(super::github_token_help_context(
            GitHubMode::ProjectsV2,
            Some(&parsed),
        ))
        .join("\n");

        assert!(lines.contains("classic PAT"));
        assert!(lines.contains("`project`"));
        assert!(lines.contains("`read:project`"));
        assert!(lines.contains("not a fine-grained PAT"));
    }

    #[test]
    fn github_token_help_mentions_fine_grained_pat_for_org_owned_projects_v2() {
        let parsed = super::parse_project_url("https://github.com/orgs/acme/projects/12").unwrap();
        let lines = super::github_token_help_lines(super::github_token_help_context(
            GitHubMode::ProjectsV2,
            Some(&parsed),
        ))
        .join("\n");

        assert!(lines.contains("fine-grained PAT may work"));
        assert!(lines.contains("`Projects` permission"));
        assert!(lines.contains("classic PAT also works"));
    }

    #[test]
    fn github_token_help_mentions_classic_pat_fallback_when_project_ownership_is_unknown() {
        let lines = super::github_token_help_lines(super::github_token_help_context(
            GitHubMode::ProjectsV2,
            None,
        ))
        .join("\n");

        assert!(lines.contains("User-owned Projects v2 require a classic PAT"));
        assert!(lines.contains("fine-grained PAT"));
        assert!(lines.contains("create a classic PAT instead"));
    }

    #[test]
    fn github_token_help_mentions_repo_scope_for_issues_only() {
        let lines = super::github_token_help_lines(super::github_token_help_context(
            GitHubMode::IssuesOnly,
            None,
        ))
        .join("\n");

        assert!(lines.contains("`repo`"));
        assert!(!lines.contains("`read:project`"));
    }

    #[test]
    fn project_status_handling_help_explains_safe_default() {
        let lines =
            super::project_status_help_lines(super::ProjectStatusHelpTopic::Handling).join("\n");

        assert!(lines.contains("existing Project statuses"));
        assert!(lines.contains("safe default"));
        assert!(lines.contains("does not mutate GitHub"));
    }

    #[test]
    fn project_status_active_states_help_explains_dispatch_queue() {
        let lines = super::project_status_help_lines(super::ProjectStatusHelpTopic::ActiveStates)
            .join("\n");

        assert!(lines.contains("working queue"));
        assert!(lines.contains("Only items in these active states are polled and dispatched"));
        assert!(lines.contains("terminal state"));
    }

    #[test]
    fn project_status_claimable_help_explains_optional_subset() {
        let lines =
            super::project_status_help_lines(super::ProjectStatusHelpTopic::ClaimableStates)
                .join("\n");

        assert!(lines.contains("subset of active states"));
        assert!(lines.contains("ready to claim right now"));
        assert!(lines.contains("Leave this empty"));
    }

    #[test]
    fn project_status_transition_help_mentions_disabling_automatic_updates() {
        let lines =
            super::project_status_help_lines(super::ProjectStatusHelpTopic::HumanReviewState)
                .join("\n");

        assert!(lines.contains("human follow-up"));
        assert!(lines.contains("Do not change project status"));
        assert!(lines.contains("disable that automatic transition"));
    }

    #[test]
    fn setup_auto_replaces_remote_docker_workflow_placeholder() {
        let dir = tempdir().unwrap();
        let workflow_path = dir.path().join("WORKFLOW.md");
        fs::write(&workflow_path, REMOTE_DOCKER_WORKFLOW_PLACEHOLDER).unwrap();

        write_text_file(&workflow_path, "tracker:\n  kind: github\n", false).unwrap();

        assert_eq!(
            fs::read_to_string(&workflow_path).unwrap(),
            "tracker:\n  kind: github\n"
        );
    }

    #[test]
    fn setup_auto_replaces_remote_docker_bootstrap_env() {
        let dir = tempdir().unwrap();
        let env_path = dir.path().join("docker.env");
        fs::write(
            &env_path,
            format!("{REMOTE_DOCKER_ENV_BOOTSTRAP_PREFIX}KAIRASTRA_DEPLOY_MODE=docker\n"),
        )
        .unwrap();

        write_text_file(
            &env_path,
            "KAIRASTRA_DEPLOY_MODE=docker\nOPENAI_API_KEY=\n",
            false,
        )
        .unwrap();

        assert_eq!(
            fs::read_to_string(&env_path).unwrap(),
            "KAIRASTRA_DEPLOY_MODE=docker\nOPENAI_API_KEY=\n"
        );
    }

    #[test]
    fn canonical_project_statuses_have_matching_terminal_options() {
        let options = super::canonical_project_status_options();
        for state in super::canonical_project_status_config().terminal_states {
            if state.eq_ignore_ascii_case("closed") {
                continue;
            }
            assert!(
                options.iter().any(|option| option == &state),
                "missing canonical status option for {state}"
            );
        }
    }
}
