#!/usr/bin/env bash
set -euo pipefail

umask 077

DEFAULT_REPO_URL="https://github.com/dbachko/kairastra.git"
DEFAULT_GIT_REF="main"
DEFAULT_INSTALL_DIR="${HOME}/kairastra"

repo_url="$DEFAULT_REPO_URL"
git_ref="$DEFAULT_GIT_REF"
install_dir="$DEFAULT_INSTALL_DIR"
reconfigure=false
skip_auth=false

usage() {
  cat <<'EOF'
Usage:
  install-remote-docker.sh [--repo <git-url>] [--ref <git-ref>] [--install-dir <path>] [--reconfigure] [--skip-auth]

Bootstraps or upgrades a Docker-based Kairastra install on a remote machine.

Options:
  --repo <git-url>       Repository to clone. Default: https://github.com/dbachko/kairastra.git
  --ref <git-ref>        Branch, tag, or ref to deploy. Default: main
  --install-dir <path>   Managed install root. Default: ~/kairastra
  --reconfigure          Re-run the interactive Kairastra setup wizard.
  --skip-auth            Skip the post-start auth menu.
  --help                 Show this help text.
EOF
}

log() {
  printf '==> %s\n' "$*"
}

die() {
  printf 'error: %s\n' "$*" >&2
  exit 1
}

require_command() {
  local name="$1"
  command -v "$name" >/dev/null 2>&1 || die "required command not found: $name"
}

maybe_resolve_github_token() {
  if [[ -n "${GITHUB_TOKEN:-}" ]]; then
    printf '%s' "${GITHUB_TOKEN}"
    return 0
  fi

  if [[ -n "${GH_TOKEN:-}" ]]; then
    printf '%s' "${GH_TOKEN}"
    return 0
  fi

  if command -v gh >/dev/null 2>&1; then
    local token
    token="$(gh auth token 2>/dev/null || true)"
    token="${token//$'\r'/}"
    token="${token//$'\n'/}"
    if [[ -n "$token" ]]; then
      printf '%s' "$token"
      return 0
    fi
  fi

  return 1
}

validate_repo_url() {
  local value="$1"
  [[ -n "$value" ]] || die "repository URL must not be empty"
  [[ "$value" != -* ]] || die "repository URL must not start with '-'"
  [[ "$value" != *[[:space:]]* ]] || die "repository URL must not contain whitespace"
}

validate_git_ref() {
  local value="$1"
  [[ -n "$value" ]] || die "git ref must not be empty"
  [[ "$value" != -* ]] || die "git ref must not start with '-'"
  [[ "$value" != *[[:space:]]* ]] || die "git ref must not contain whitespace"
}

have_tty() {
  [[ -r /dev/tty && -w /dev/tty ]]
}

with_tty() {
  "$@" < /dev/tty
}

sanitize_compose_project() {
  local raw="$1"
  local sanitized
  sanitized="$(printf '%s' "$raw" | tr '[:upper:]' '[:lower:]' | tr -cs 'a-z0-9' '-')"
  sanitized="${sanitized#-}"
  sanitized="${sanitized%-}"
  if [[ -z "$sanitized" ]]; then
    sanitized="kairastra"
  fi
  printf '%s' "$sanitized"
}

resolve_absolute_path() {
  local path="$1"
  mkdir -p "$path"
  (
    cd "$path"
    pwd -P
  )
}

write_bootstrap_env() {
  local path="$1"
  local workflow_file="$2"
  local seed_repo="$3"
  local github_token="$4"

  cat > "$path" <<EOF
# Bootstrap env generated by install-remote-docker.sh.
# Re-run \`kairastra setup --mode docker\` to replace this file with a fully configured version.
KAIRASTRA_DEPLOY_MODE=docker
GITHUB_TOKEN=${github_token}
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
GEMINI_API_KEY=${GEMINI_API_KEY:-}
OPENAI_API_KEY=${OPENAI_API_KEY:-}
CLAUDE_CODE_OAUTH_TOKEN=${CLAUDE_CODE_OAUTH_TOKEN:-}
CODEX_AUTH_MODE=auto
CLAUDE_AUTH_MODE=auto
GEMINI_AUTH_MODE=auto
KAIRASTRA_CLAUDE_KEYRING_PASSWORD=${KAIRASTRA_CLAUDE_KEYRING_PASSWORD:-}
WORKFLOW_FILE=${workflow_file}
SEED_REPO_PATH=${seed_repo}
KAIRASTRA_WORKSPACE_ROOT=/workspaces
RUST_LOG=info
KAIRASTRA_GITHUB_OWNER=
KAIRASTRA_GITHUB_REPO=
KAIRASTRA_GITHUB_PROJECT_NUMBER=
KAIRASTRA_GITHUB_PROJECT_URL=
KAIRASTRA_GIT_CLONE_URL=${repo_url}
KAIRASTRA_GIT_PUSH_URL=
KAIRASTRA_AGENT_ASSIGNEE=
KAIRASTRA_GIT_AUTHOR_NAME=Kairastra
KAIRASTRA_GIT_AUTHOR_EMAIL=kairastra@users.noreply.github.com
KAIRASTRA_CODEX_MODEL=
KAIRASTRA_CODEX_REASONING_EFFORT=
KAIRASTRA_CODEX_FAST=false
KAIRASTRA_CLAUDE_MODEL=
KAIRASTRA_CLAUDE_REASONING_EFFORT=
KAIRASTRA_GEMINI_MODEL=
KAIRASTRA_GEMINI_APPROVAL_MODE=yolo
CODEX_CLI_VERSION=0.114.0
CLAUDE_CODE_VERSION=2.1.81
GEMINI_CLI_VERSION=0.35.0
EOF
  chmod 600 "$path"
}

sync_repo_checkout() {
  local repo_dir="$1"

  if [[ -d "$repo_dir/.git" ]]; then
    log "Updating managed checkout in $repo_dir"
    git -C "$repo_dir" remote set-url origin "$repo_url"
    git -C "$repo_dir" fetch --tags --prune origin
  else
    log "Cloning $repo_url into $repo_dir"
    git clone -- "$repo_url" "$repo_dir"
  fi

  if git -C "$repo_dir" show-ref --verify --quiet "refs/remotes/origin/$git_ref"; then
    git -C "$repo_dir" checkout --force -B "$git_ref" "origin/$git_ref"
  else
    git -C "$repo_dir" checkout --force "$git_ref"
  fi
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --repo)
      [[ $# -ge 2 ]] || die "--repo requires a value"
      repo_url="$2"
      shift 2
      ;;
    --ref)
      [[ $# -ge 2 ]] || die "--ref requires a value"
      git_ref="$2"
      shift 2
      ;;
    --install-dir)
      [[ $# -ge 2 ]] || die "--install-dir requires a value"
      install_dir="$2"
      shift 2
      ;;
    --reconfigure)
      reconfigure=true
      shift
      ;;
    --skip-auth)
      skip_auth=true
      shift
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      die "unknown argument: $1"
      ;;
  esac
done

require_command git
require_command docker
docker compose version >/dev/null 2>&1 || die "docker compose is required"
validate_repo_url "$repo_url"
validate_git_ref "$git_ref"

install_dir="$(resolve_absolute_path "$install_dir")"
repo_dir="${install_dir}/repo"
config_dir="${install_dir}/config"
workflow_path="${config_dir}/WORKFLOW.md"
env_path="${config_dir}/docker.env"
compose_project="$(sanitize_compose_project "$(basename "$install_dir")")"
github_token="$(maybe_resolve_github_token || true)"

mkdir -p "$config_dir"

sync_repo_checkout "$repo_dir"

if [[ ! -f "$workflow_path" ]]; then
  cat > "$workflow_path" <<'EOF'
# Generated placeholder for remote Kairastra install.
# The setup wizard will replace this file.
EOF
  chmod 600 "$workflow_path"
fi

if [[ ! -f "$env_path" ]]; then
  write_bootstrap_env "$env_path" "$workflow_path" "$repo_dir" "$github_token"
fi

compose_args=(
  -p "$compose_project"
  -f "$repo_dir/rust/compose.yml"
  --env-file "$env_path"
)

docker_compose() {
  docker compose "${compose_args[@]}" "$@"
}

setup_required=false
if ! grep -q '^# Generated by `kairastra setup`$' "$env_path" 2>/dev/null; then
  setup_required=true
fi

if [[ "$reconfigure" == "true" || "$setup_required" == "true" ]]; then
  have_tty || die "interactive setup requires a TTY; re-run over SSH with -t"
fi

if [[ "$skip_auth" == "false" && ( "$reconfigure" == "true" || "$setup_required" == "true" ) ]]; then
  have_tty || die "interactive auth requires a TTY; re-run over SSH with -t or pass --skip-auth"
fi

log "Building the Kairastra Docker image"
docker_compose build

if [[ "$reconfigure" == "true" || "$setup_required" == "true" ]]; then
  log "Running the interactive Docker setup wizard"
  with_tty docker_compose run --rm \
    -v "$config_dir:/config-state" \
    -e "KAIRASTRA_SEED_REPO=$repo_dir" \
    -e "KAIRASTRA_GIT_CLONE_URL=$repo_url" \
    kairastra setup --mode docker --workflow /config-state/WORKFLOW.md --env-file /config-state/docker.env
fi

log "Running Docker doctor checks"
docker_compose run --rm \
  -v "$config_dir:/config-state" \
  kairastra doctor --mode docker --workflow /config-state/WORKFLOW.md --env-file /config-state/docker.env

log "Starting or refreshing the Kairastra stack"
docker_compose up -d --remove-orphans

if [[ "$skip_auth" == "false" && ( "$reconfigure" == "true" || "$setup_required" == "true" ) ]]; then
  log "Opening the provider auth menu"
  with_tty docker_compose run --rm kairastra auth menu
fi

printf '\n'
printf 'Kairastra is installed in %s\n' "$install_dir"
printf 'Managed checkout: %s\n' "$repo_dir"
printf 'Config directory: %s\n' "$config_dir"
printf '\n'
printf 'Common commands:\n'
printf '  Logs:        docker compose -p %s -f %s --env-file %s logs -f kairastra\n' "$compose_project" "$repo_dir/rust/compose.yml" "$env_path"
printf '  Doctor:      docker compose -p %s -f %s --env-file %s run --rm -v %s:/config-state kairastra doctor --mode docker --workflow /config-state/WORKFLOW.md --env-file /config-state/docker.env\n' "$compose_project" "$repo_dir/rust/compose.yml" "$env_path" "$config_dir"
printf '  Restart:     docker compose -p %s -f %s --env-file %s up -d --remove-orphans\n' "$compose_project" "$repo_dir/rust/compose.yml" "$env_path"
printf '  Re-run:      %s --install-dir %s --repo %s --ref %s\n' "$repo_dir/scripts/install-remote-docker.sh" "$install_dir" "$repo_url" "$git_ref"
printf '  Reconfigure: %s --install-dir %s --repo %s --ref %s --reconfigure\n' "$repo_dir/scripts/install-remote-docker.sh" "$install_dir" "$repo_url" "$git_ref"
